LICENSE

Updates year and developers in the license

License Update

---

.pre-commit-config.yaml

Bumping version of the packages providing pere-commit checks.

[MNT] Bump versions of pre-commit checks 

---

docs/source/get_involved/governance.rst

[GOV] Removed CC Observer role

---

docs/source/api_reference/dists_kernels.rst
docs/source/api_reference/performance_metrics.rst
docs/source/api_reference/transformations.rst
docs/source/conf.py
docs/source/examples.rst
pyproject.toml
sktime/annotation/ggs.py
sktime/tests/_config.py

- fixes #72 
There were import errors and outdated dependencies breaking the build of documentation. This PR corrects the broken imports and bumps the version do `docs` dependency group.

[BUG] Fix documentation build errors 

---

docs/source/get_involved/governance.rst

[GOV] proposal: CC and CoC should have disjoint membership

---

sktime/annotation/clasp.py
sktime/transformations/series/clasp.py

This addresses some bugs in ClaSP:
- Adds a warning if the window size is larger than the time series
- Checks if there are enough points left to do a segmentation

[Bug] ClaSP Bugfixes

---

docs/source/get_involved/governance.rst

[GOV] Appointment of CC and CoC members

---

sktime/transformations/series/adapt.py

current docstring looks horribly rendered, trying at least to improve a bit

[DOC] Fix docstring of TabularToSeriesAdaptor

---

sktime/distances/_distance.py
sktime/distances/_dtw.py
sktime/distances/_euclidean.py
sktime/distances/_numba_utils.py

Elastic Ensemble was among the slowest methods in CI. 
The root cause are closures in numba, which are recompiled upon every call.
This PR fixes the numba closure issue.

[ENH] [BUG] Improving Runtime of Elastic Ensemble by 20x (by fixing the closure issue)

---

.github/workflows/test.yml
.github/workflows/wheels.yml
build_tools/check_install_from_test_pypi.sh
docs/source/installation.rst
pyproject.toml
sktime/forecasting/compose/tests/test_ensemble.py
sktime/forecasting/theta.py

[MNT] Remove Python 3.7 support

---

sktime/transformations/series/feature_selection.py
sktime/transformations/series/tests/test_feature_selection.py

[MNT] Fix random test failure in FeatureSelection

---

aeon/annotation/adapters/__init__.py
aeon/annotation/adapters/_pyod.py
aeon/annotation/base/__init__.py
aeon/annotation/base/_base.py
aeon/annotation/clasp.py
aeon/annotation/datagen.py
aeon/annotation/hmm_learn/__init__.py
aeon/annotation/hmm_learn/gaussian.py
aeon/annotation/hmm_learn/gmm.py
aeon/annotation/hmm_learn/poisson.py
aeon/annotation/plotting/__init__.py
aeon/annotation/plotting/utils.py
aeon/annotation/stray.py
aeon/classification/base.py
aeon/classification/compose/_channel_ensemble.py
aeon/classification/compose/_ensemble.py
aeon/classification/compose/_pipeline.py
aeon/classification/convolution_based/_arsenal.py
aeon/classification/dictionary_based/_boss.py
aeon/classification/dictionary_based/_cboss.py
aeon/classification/dictionary_based/_weasel.py
aeon/classification/dictionary_based/_weasel_v2.py
aeon/classification/distance_based/_shape_dtw.py

A few automated refactoring in the annotation and classification modules.

[MNT] Automated refactorings

---

docs/source/conf.py

This shouldn't have been removed.

[DOC] Add website warning again.

---

README.md
aeon/__init__.py
pyproject.toml

A pre-release for 0.1.0. No change log yet.

Pre-release 0.1.0rc0

---

README.md
docs/source/conf.py

[FORK] Fix disclaimer

---

docs/source/about/artwork.rst
docs/source/about/citation.md
docs/source/about/showcase.rst
docs/source/roadmap.rst

closes https://github.com/aeon-toolkit/aeon/issues/231
closes https://github.com/aeon-toolkit/aeon/issues/233
closes https://github.com/aeon-toolkit/aeon/issues/230
closes https://github.com/aeon-toolkit/aeon/issues/229

[DOC] Fix rename aeon/sktime

---

aeon/classification/feature_based/_tsfresh_classifier.py
aeon/transformations/panel/tsfresh.py
pyproject.toml

https://github.com/blue-yonder/tsfresh/issues/991

[MNT] Remove Python version restriction of tsfresh

---

docs/conf.py

Current disclaimer doesn't show for markdown files, hopefully this does.

[DOC] Disclaimer for markdown

---

aeon/regression/_delegate.py
aeon/regression/base.py
aeon/regression/dummy/_dummy.py
aeon/regression/interval_based/_tsf.py
setup.cfg

Remove all references to nested_univ from the regression module, only actual change is internal type for DummyRegressor, for which I have removed an unnecessary data allocation in fit 
#110

[ENH] remove regression mentions of nested_univ

---

README.md

Adds the following to the GitHub README:
1. aeon logo at the top
2. Additional buttons available with the PyPI release
3. Introduction text alongside link to release notes and documentation
4. Simple installation instructions
Best viewed at https://github.com/aeon-toolkit/aeon/tree/readme

[DOC] Update README

---

aeon/classification/deep_learning/inception_time.py
aeon/tests/_config.py

[BUG] Fix test overwrite inception time classifier

---

aeon/classification/deep_learning/inception_time.py

Check InceptionTime from the list in #320

[ENH] added ReduceLROnPlateau callback by default to InceptionTime deep classifier

---

aeon/transformations/panel/rocket/_minirocket.py
aeon/transformations/panel/rocket/_minirocket_multivariate.py
aeon/transformations/panel/rocket/_multirocket.py
aeon/transformations/panel/rocket/_multirocket_multivariate.py

[DOC] Fix rocket examples imports

---

aeon/classification/deep_learning/fcn.py
aeon/classification/deep_learning/mlp.py
aeon/classification/deep_learning/resnet.py

[ENH] Add reduce on plateau learning rate decay for FCN ResNet and MLP deep classifiers

---

.github/workflows/release.yml
.github/workflows/test.yml
aeon/transformations/series/tests/test_kalman_filter.py
pyproject.toml

fixes #155 
This PR is extending the CI coverage to python 3.11. It is probably going to fail until numba support python 3.11 - more details in the issue #155.

[MNT] Add python 3.11 support

---

aeon/regression/deep_learning/inception_time.py

[ENH] added modelcheckpoint and reduce learning rate to inceptionTime regressor

---

aeon/classification/deep_learning/cnn.py
aeon/classification/deep_learning/encoder.py
aeon/classification/deep_learning/fcn.py
aeon/classification/deep_learning/inception_time.py
aeon/classification/deep_learning/mlp.py
aeon/classification/deep_learning/resnet.py

Fix #321 
Adds the model checkpoint callback to save the best model for all of the deep learning classifiers
I did not touch the `tapenet` classifier given that it was proposed for multivariate time series (to the best of my knowledge) and I did not want to make any changes that I shouldn't do, if you want I can add the changes, PS: am not a code author of `tapenet`, but for all the others I grantee the changes I am doing.

[ENH] Add model checkpoint for the rest of the deep learning classifiers

---

.all-contributorsrc
aeon/benchmarking/benchmarks.py
aeon/benchmarking/forecasting.py
aeon/benchmarking/tests/test_benchmarks.py
aeon/benchmarking/tests/test_forecasting.py
examples/04_benchmarking_v2.ipynb
pyproject.toml

https://github.com/aeon-toolkit/aeon/issues/116 for general context. 
https://github.com/aeon-toolkit/aeon/issues/116#issuecomment-1509958967 for context specific to this PR and implementation.  
- a core benchmarking module
- forecasting benchmarking module (using the core module)
- unit tests
- example notebook showing usage
Optional, to `all_extras`: `kotsu>=0.3.1`
Reviewing the example notebook first to get a sense of usage of the API and if it fits with how you envisaged it.
Then the implementation.  
Considerations for further work: 
- Deleting/archiving all the previous benchmarking code?
- Implementing benchmarking modules for classification, clustering, etc.
Yes.

[ENH] Implement simple(r) benchmarking

---

aeon/classification/deep_learning/resnet.py

Fix #420 
Part of #421  and #395

[BUG] refactored params usage resnet

---

README.md

Adds a bright disclaimer to the README indicating that the deprecation policy is currently suspended.

[DOC] README deprecation policy disclaimer

---

README.md
docs/getting_started.md

Adds a section to the GitHub README pointing to the webpage and providing two small examples for forecasting and classification.
Fixes small issues with the webpage examples.

[DOC] README getting started section

---

aeon/utils/numba/general.py
aeon/utils/numba/stats.py

Adds some new numba utility functions, and adds examples to most existing ones.

[ENH] `numba` utility functions

---

aeon/classification/base.py
aeon/classification/convolution_based/_arsenal.py
aeon/classification/dictionary_based/_muse.py
aeon/classification/dictionary_based/_tde.py
aeon/classification/dictionary_based/_weasel.py
aeon/classification/distance_based/_elastic_ensemble.py
aeon/classification/early_classification/_probability_threshold.py
aeon/classification/early_classification/_teaser.py
aeon/classification/early_classification/base.py
aeon/classification/feature_based/_fresh_prince.py
aeon/classification/feature_based/_matrix_profile_classifier.py
aeon/classification/feature_based/_summary_classifier.py
aeon/classification/feature_based/_tsfresh_classifier.py
aeon/classification/hybrid/_hivecote_v1.py
aeon/classification/hybrid/_hivecote_v2.py
aeon/classification/interval_based/_cif.py
aeon/classification/interval_based/_drcif.py
aeon/classification/interval_based/_random_interval_classifier.py
aeon/classification/interval_based/_rise.py
aeon/classification/interval_based/_stsf.py
aeon/classification/shapelet_based/_stc.py
aeon/regression/base.py
examples/loading_data.ipynb
extension_templates/classification.py
extension_templates/clustering.py
setup.cfg

fixes #102 
Simple refactor of _n_threads_to_use to _n_jobs

[ENH] refactor _threads_to_use to _n_jobs

---

aeon/classification/ordinal_classification/_ordinal_tde.py

Changes the Ordinal TDE `_threads_to_use` to `_n_jobs`.
See #101.

[BUG] Ordinal TDE _n_jobs

---

aeon/classification/shapelet_based/__init__.py
aeon/classification/shapelet_based/_mrsqm.py
pyproject.toml

Wraps the MrSQM classifier from https://github.com/mlgig/mrsqm.

[ENH] MrSQM classification wrapper

---

aeon/transformations/collection/dictionary_based/_paa.py
aeon/transformations/collection/dictionary_based/_sax.py
aeon/transformations/collection/dictionary_based/tests/test_paa.py

Part of #434 
Refactors PAA to become faster
The only input parameter is the number of segments, or in other words, the target dimension.
Basically for the transformation can be done in:
- One line, parallelized over all samples and dimensions if and only if the length of the TS is divisible by the number of segments
- A for loop on the segments split indices, still parallelized, only in the case of non divisibility
The optimality and correctness of the PAA refactor
Refactored the PAA test

[ENH] Refactoring PAA

---

aeon/classification/deep_learning/inception_time.py

changes series_length -> n_timepoints and tests if Ali is notified.

[DOC] InceptionTime docstrings

---

aeon/datasets/__init__.py
aeon/datasets/_data_generators.py
aeon/datatypes/tests/test_panel_converters.py

Part of #499.
Essentially wraps the testing data generator for 3D numpy but is public facing. Updates a few parameter named from `series_length` to `n_timepoints`.

[ENH] Add function to make example 3D numpy problems

---

aeon/classification/hybrid/__init__.py
aeon/classification/hybrid/_hivecote_v1.py
aeon/classification/hybrid/_hivecote_v2.py

It is currently possible to have a cv size of 1 in HC1, which will crash fit. Adds some parameter documentation.

[BUG] HIVECOTEV1 cross-validation bugfix

---

.gitignore
README.md
docs/conf.py
docs/getting_started.md
pyproject.toml

Adds 2 sections to the getting started page for transformers and collection transformers.
Adds a package to automatically generate [Open Graph metadata](https://ogp.me/) for each page. This package was recommended by the Furo dev and I don't see any harm in adding it.

[DOC] Add transformations to getting started page and add opengraph sphinx package

---

aeon/classification/deep_learning/__init__.py
aeon/networks/__init__.py
aeon/regression/deep_learning/__init__.py

adds all deep learning estimators to init files, to stop warnings like this
https://readthedocs.org/projects/aeon-toolkit/builds/21239525/

[ENH] Add deep networks/classifiers/regressors to init

---

aeon/regression/deep_learning/__init__.py
aeon/regression/deep_learning/resnet.py

Part of #225 
Adding resnet here

[ENH] Add ResNet deep learning regressor

---

aeon/regression/deep_learning/__init__.py
aeon/regression/deep_learning/fcn.py

Part of #225 
Add FCN to regression deep learning module

[ENH] Add FCN deep learning regressor

---

aeon/regression/deep_learning/cnn.py

Part of #225 
Fixing CNN regressor to use all params of CNN network and add output activation, the model was using a weird activation setup where its the same for convolutions and output

[MNT-ENH] Fixed stuff in CNN deep learning regressor

---

.all-contributorsrc
aeon/utils/_maint/_show_versions.py

[BUG] Update _show_versions.py (aeon-toolkit#670)

---

aeon/networks/tests/test_network_base.py

[ENH] Add a test for network module

---

aeon/transformations/collection/signature_based/_augmentations.py
aeon/transformations/collection/signature_based/_compute.py
aeon/transformations/collection/signature_based/_signature_method.py

Swaps the `SignatureTransformer` classes over to the collection base class.

[ENH] Change signature transform base class to `BaseCollectionTransformer`

---

aeon/transformations/collection/dictionary_based/_sfa.py
aeon/transformations/collection/dictionary_based/tests/test_sfa.py

This PR fixes the bug #626 with numba's typed dict in SFA when numba is disabled via a global variable.

[BUG] Fixes a bug with numba's typed dict in SFA when numba is disabled

---

aeon/distances/tests/__init__.py
aeon/distances/tests/test_alignment_path.py
aeon/distances/tests/test_cost_matrix.py
aeon/distances/tests/test_distances.py
aeon/distances/tests/test_pairwise.py
setup.cfg

[BUG] shapedtw using assert_almost_equal in test_distances

---

.github/workflows/pr_pre_commit.yml

As the title says. It should ease the burden a bit for those who have not set up properly yet. Won't catch everything, though.

[MNT] Add pre-commit bot which pushes fixes to PRs

---

sweep.yaml

Hey guys, I'm Kevin from Sweep. 
Just updated the sandbox configuration to check only the file that was modified as opposed to all files, limiting the chance of Sweep modifying a file it wasn't intending to modify.
N/A
N/A
N/A

[ENH] Update sweep.yaml to improve Sweep Sandbox

---

docs/papers_using_aeon.md

adds some papers to papers using aeon

[DOC] add papers to papers using aeon page

---

.all-contributorsrc
.github/workflows/pr_pytest.yml
.github/workflows/release.yml
aeon/benchmarking/results_plotting.py
aeon/classification/dictionary_based/_tde.py
aeon/classification/ordinal_classification/_ordinal_tde.py
aeon/transformations/collection/dictionary_based/_sfa.py
aeon/transformations/collection/dictionary_based/tests/test_sfa.py
conftest.py

A few bugfixes and actions maintenance to help with bugfixing:
- Uses the `_typed_dict` method from SFA for handling disabled numba in TDE also
- Changes the parameter used in the boxplot function from `lw` to `linewidth`
- Introduces labels to run the full test suite in PRs and the code coverage test
- Removes the `test_typed_dict_disabled_numba` test from #753. I think this is sufficiently handled with the coverage/periodic actions (which include both with and without numba) and the current SFA test functions (which test both True and False for the typed dict). This is more me not trusting Python with handling the setting of environment variables while pytest is doing threading stuff than disliking the test 🙂 
@TonyBagnall @patrickzib feel free to make suggestions on the bugfixes and …

[BUG] TDE and boxplot bugfixes

---

README.md
docs/getting_started.md

a couple of typos I found whilst distracting myself from proper work.

[DOC] A couple of typos

---

aeon/networks/cnn.py
aeon/networks/encoder.py
aeon/networks/fcn.py
aeon/networks/inception.py
aeon/networks/mlp.py
aeon/networks/resnet.py
aeon/networks/tapnet.py

[DOC] network docstrings

---

aeon/transformations/collection/base.py
aeon/transformations/collection/tests/test_base.py

fixes #807 
adds tests for inverse_transform, fixes an incorrect method call

[ENH] Bug and coverage for BaseCollectionTransformer

---

sweep.yaml

[MNT] Update sweep.yaml

---

.github/workflows/pr_pytest.yml

This currently fails due to running the data loading tests.

[MNT] Add PR testing to `test-nosoftdeps-full`

---

.github/PULL_REQUEST_TEMPLATE.md

Updates the current pull request template. Edits spacing to make it a bit easier to read and updates some out of date parts.
Removes the `What should a reviewer concentrate their feedback on?` and `Did you add any tests for the change?` sections which add more bloat to the template than they are worth IMO. Can add them back if people disagree.
Splits up the checklist into different sections, as not all of the items apply to all contributions/contributors,

[MNT] Update Pull Request template

---

aeon/regression/compose/_pipeline.py
aeon/transformations/collection/shapelet_based/tests/test_shapelet_transform.py

current example times out without numba.

[ENH] Speed up regression pipeline example

---

aeon/clustering/deep_learning/ae_fcn.py
aeon/clustering/deep_learning/base.py

Change test params of `AEFCNClusterer` given the timeout on overnighter https://github.com/aeon-toolkit/aeon/actions/runs/6648384594/job/18065326220

[MNT] Reduce test params for `AEFCNClusterer`

---

sweep.yaml

Update sweep.yaml to disable rules and fix sandbox

---

aeon/clustering/deep_learning/ae_fcn.py

fixing [this](https://github.com/aeon-toolkit/aeon/actions/runs/6687290173/job/18167760246)

[MNT] Replacing BA by Mean in AEFCNClusterer test params

---

sweep.yaml

This updates the sweep.yaml to open draft PRs.
No
- [ x] I've added myself to the [list of contributors](https://github.com/aeon-toolkit/aeon/blob/main/.all-contributorsrc). Alternatively, you can use the [@all-contributors](https://allcontributors.org/docs/en/bot/usage) bot to do this for you.
- [x ] The PR title starts with either [ENH], [MNT], [DOC], [BUG], [REF] or [GOV] indicating whether the PR topic is related to enhancement, maintenance, documentation, bugs, refactoring or governance.

[ENH] Set Draft to true in sweep.yaml

---

sweep.yaml

This updates the sweep.yaml to fix the spacing.
No
- [ x] I've added myself to the [list of contributors](https://github.com/aeon-toolkit/aeon/blob/main/.all-contributorsrc). Alternatively, you can use the [@all-contributors](https://allcontributors.org/docs/en/bot/usage) bot to do this for you.
- [x ] The PR title starts with either [ENH], [MNT], [DOC], [BUG], [REF] or [GOV] indicating whether the PR topic is related to enhancement, maintenance, documentation, bugs, refactoring or governance.

[BUG] Update sweep.yaml spacing

---

aeon/classification/deep_learning/inception_time.py
aeon/networks/inception.py
aeon/regression/deep_learning/inception_time.py

basically setting the `use_custom_filters` argument to False in Network/Classification/Regression Inception/InceptionTime

[MNT] Default InceptionTime to use original model and not H version

---

aeon/classification/deep_learning/__init__.py
aeon/classification/deep_learning/lite_time.py
aeon/networks/inception.py
aeon/networks/lite.py

Adding LITE and LITETime from [LITE: Light Inception with boosTing tEchniques for Time Series Classification](https://ieeexplore.ieee.org/abstract/document/10302569)
Same setup as the rest.

[ENH] Adding LITETime for Deep Learning classifiers

---

aeon/visualisation/results_plotting.py

[ENH] scatter plots enhancement. 

---

aeon/performance_metrics/clustering.py
aeon/performance_metrics/tests/test_clustering_metrics.py

Solves #1037.
Just uses a Python file instead of a package.

[ENH] Add `clustering_accuracy_score` to metrics

---

aeon/classification/dictionary_based/_redcomets.py

Updates the paper reference in the RED CoMETS documentation from the ArXiV preprint to the official conference proceedings.

[DOC] Updated paper reference for RED CoMETS

---

.binder/Dockerfile
.github/PULL_REQUEST_TEMPLATE.md
CHANGELOG.md
CODE_OF_CONDUCT.md
CONTRIBUTING.md
GOVERNANCE.md
README.md
build_tools/pr_labeler.py

Fixes #1064 and does a bit of general tidying.

[DOC,MNT] Tidy up GitHub txt links and update dockerfile version

---

build_tools/pr_labeler.py
build_tools/pr_open_commenter.py

It's pretty annoying. Also adds tags to the all contributors bot PRs

[MNT] Stop the bot from commenting on other bots PRs

---

aeon/classification/dictionary_based/tests/test_redcomets.py
aeon/classification/dictionary_based/tests/test_weasel.py
aeon/classification/tests/test_sklearn_compatability.py
pyproject.toml

Updates the sklearn version bound to allow version 1.4.0.

[ENH] Update `scikit-learn` version

---

aeon/performance_metrics/stats.py
aeon/performance_metrics/tests/test_stats.py
aeon/visualisation/results/_significance.py

This PR solves some comments left by @MatthewMiddlehurst  in #954.

[ENH, MNT] Changes to docs in significance plots and stats.

---

docs/changelog.md

Fix broken links in changelog docs. They were ending with an additional `>` character, leading to 404 error.

[DOC] Fix broken links in changelog.md

---

aeon/classification/convolution_based/_arsenal.py
aeon/classification/convolution_based/_rocket_classifier.py

Fixes #1153 
I have refactored series_length and n_instances to n_timepoints and n_cases in convolution based classifiers
Please let me know if any more changes are required

[ENH] Refactored series_length and n_instances to n_timepoints and n_cases

---

aeon/base/estimator/interval_based/base_interval_forest.py
aeon/datasets/_data_writers.py

Fixes #1148 and #1149 
I have done the required changes. Please let me know if more changes are required.
Thanks

[ENH] Refactored n_instances to n_cases and series_length to n_timepoints

---

aeon/classification/interval_based/__init__.py
aeon/classification/interval_based/_quant.py
aeon/classification/interval_based/tests/__init__.py
aeon/classification/interval_based/tests/test_quant.py
aeon/transformations/collection/interval_based/__init__.py
aeon/transformations/collection/interval_based/_quant.py
docs/api_reference/classification.rst
pyproject.toml

Implements a `QUANTClassifier` and `QUANTTransformer` estimator. Paper source [here](https://arxiv.org/abs/2308.00928).

[ENH] QUANT classifier and transformer

---

aeon/classification/deep_learning/_cnn.py
aeon/classification/deep_learning/_encoder.py
aeon/classification/deep_learning/_fcn.py
aeon/classification/deep_learning/_mlp.py
aeon/classification/deep_learning/_resnet.py
aeon/classification/deep_learning/_tapnet.py
aeon/clustering/deep_learning/_ae_fcn.py
aeon/clustering/deep_learning/_ae_resnet.py
aeon/networks/_ae_fcn.py
aeon/networks/_ae_resnet.py
aeon/networks/_cnn.py
aeon/networks/_encoder.py
aeon/networks/_fcn.py
aeon/networks/_inception.py
aeon/networks/_lite.py
aeon/networks/_mlp.py
aeon/networks/_resnet.py
aeon/networks/_tapnet.py
aeon/regression/deep_learning/_cnn.py
aeon/regression/deep_learning/_fcn.py
aeon/regression/deep_learning/_inception_time.py
aeon/regression/deep_learning/_resnet.py
aeon/regression/deep_learning/_tapnet.py

[MNT] Remove random_state from aeon.networks module

---

aeon/classification/distance_based/_shape_dtw.py

fixes: #1152
Reformatted the docstrings as per AEON's conventions.

[DOC] updated shapedtw

---

.all-contributorsrc
aeon/classification/deep_learning/_cnn.py
aeon/classification/deep_learning/_encoder.py
aeon/classification/deep_learning/_fcn.py
aeon/classification/deep_learning/_inception_time.py
aeon/classification/deep_learning/_lite_time.py
aeon/classification/deep_learning/_mlp.py
aeon/classification/deep_learning/_resnet.py
aeon/classification/deep_learning/_tapnet.py
aeon/classification/distance_based/_shape_dtw.py
aeon/regression/deep_learning/_cnn.py
aeon/regression/deep_learning/_fcn.py
aeon/regression/deep_learning/_inception_time.py
aeon/regression/deep_learning/_resnet.py
aeon/regression/deep_learning/_tapnet.py

conformed the `_fit` function from `classification\deep_learning`  to new standards of Aeon's docstrings
closes: #1150

[DOC] Conformed to new-standards

---

aeon/forecasting/tests/test_interval_wrappers.py
examples/benchmarking/reference_results.ipynb
examples/similarity_search/code_speed.ipynb

overnighter failing due to obscure datatype nonsense. 
1. precommit failing from two notebooks
2. datatypes checking function failing from mtype to scitype

precommit fix

---

docs/mentoring.md

Added a missing link, which was supposed to redirect to aeon-neuro page
No, it does not.

[DOC] Missing link for aeon-neuro

---

examples/benchmarking/benchmarking.ipynb

[DOC] Fix benchmarking notebooks

---

aeon/transformations/collection/convolution_based/_rocket.py
aeon/transformations/collection/convolution_based/rocketGPU/tests/test_base_rocketGPU.py

Refactored the test funcs to use `numpy.testing.assert_array_almost_equal` for more robust testing.
#1248 , #1272

[MNT] Modified `test_base_rocketGPU.py`

---

aeon/classification/dictionary_based/_weasel_v2.py

[DEP] remove support probabilities from weasel2

---

aeon/datasets/_data_loaders.py
aeon/datasets/tests/test_data_loaders.py

fix incorrect usage of os.join("FOO",None) in edge test configuration

[BUG] Stop joining Nones

---

aeon/classification/distance_based/_time_series_neighbors.py
aeon/regression/distance_based/_time_series_neighbors.py

fixes: #1234 
we do not need to calculate the square.

[ENH] fixed sqr error

---

aeon/clustering/deep_learning/base.py
aeon/clustering/deep_learning/tests/test_deep_clusterer_base.py

fixes: #1170 
added `KShape` and `KMedoids` to `BaseDeepClusterer`

[ENH] Modified `BaseDeepClusterer`

---

README.md

This PR adds a simple clustering example to the README

[DOC] Add clustering example to the README

---

aeon/classification/shapelet_based/_ls.py
aeon/testing/test_config.py
docs/changelogs/v0.8.md
docs/installation.md

Fixes and skips broken tests for the `LearningShapeletClassifier`. I believe the extra functions were causing some issues so they have been commented for now. The deterministic test was due to a `keras` issue, I'm not quite sure how to solve that and would rather get the release out.

[BUG] `LearningShapeletClassifier` fixes

---

aeon/datatypes/__init__.py
aeon/datatypes/_vec_df.py
aeon/datatypes/_vectorize.py
aeon/datatypes/tests/test_vectorize.py
aeon/forecasting/base/_base.py
aeon/performance_metrics/forecasting/probabilistic/_classes.py
aeon/transformations/base.py
aeon/utils/index_functions.py

Deprecates the public version and swaps usage to a private version.

[DEP] Make `VectorizedDF` private

---

docs/mentoring.md

These changes fix what looks to be mis-wording/typos in mentoring docs. Though, I'm not 100% sure what the intention was, so this PR is just to start the editing process.
No

[DOC] Fixes mis-wording/typo in mentoring docs

---

.github/workflows/github_maintenace.yml

Updates the version and label used for branch deletion.

[MNT] Update branch clean action

---

aeon/transformations/collection/pad.py
aeon/transformations/collection/tests/test_pad.py

[ENH] Add support for array-like and statistical inputs as arguments in fill_value of Padding Transformer

---

.github/actions/numba_cache/action.yml

[MNT] Update cache restore action

---

README.md
aeon/__init__.py
docs/changelogs/v0.8.md
pyproject.toml

Patch release for bugfixes and documentation changes.
Adds notices in readme and patch notes for experimental modules.
Changes some version bounds which are either redundant or broken but not covered by testing for the relevant Python version

[MNT] Release v0.8.1

---

docs/mentoring.md

added two new project, also added some links to issues, ran out of steam on distances, will finish it in a later PR

[DOC] add distance and channel selection projects

---

aeon/transformations/series/base.py
examples/base/series_estimator.ipynb

Applies the comments left after merging #1490.

[ENH] Changes to series base classes from #1490

---

docs/api_reference/classification.rst

Closes: #1497 
Adds classifiers to the existing list and arranges them in lexicographic order.

[DOC] Update classification API docs

---

aeon/transformations/scaledlogit.py
aeon/transformations/series/_scaled_logit.py
aeon/transformations/series/tests/test_scaled_logit.py

[DEP] convert Scaled Logit

---

aeon/clustering/averaging/tests/test_dba.py
pyproject.toml

This PR adds missing tests from PR #1563 
The BA weights parameter was missing tests so this PR adds those tests.
No
No

[MNT] Add tests for BA weight parameters

---

examples/classification/shapelet_based.ipynb

[DOC] Typos in shapelet notebook

---

aeon/classification/deep_learning/_mlp.py

[BUG] Fixing wrong output activation in MLPClassifier

---

aeon/anomaly_detection/_dwt_mlead.py
aeon/anomaly_detection/_merlin.py
aeon/anomaly_detection/_stray.py
aeon/anomaly_detection/base.py
docs/conf.py

none
- removes some checks from the `numpydoc` validation
- add discussion of detector learning types to `BaseAnomalyDetector`
- fixes some documentation warnings
- adds capability tables to existing detector documentations
no

[DOC] Improve anomaly detector documentation

---

aeon/classification/feature_based/_summary.py
aeon/clustering/feature_based/__init__.py
aeon/clustering/feature_based/_catch22.py
aeon/clustering/feature_based/_summary.py
aeon/clustering/feature_based/_tsfresh.py
aeon/regression/feature_based/_summary.py

Implements simple feature clusterers. Includes:
- Catch22Clusterer
- SummaryClusterer
- TSFreshClusterer

[ENH] Simple feature based clusterers

---

aeon/segmentation/__init__.py
aeon/segmentation/_fluss.py
aeon/segmentation/tests/test_all_segmenters.py
aeon/segmentation/tests/test_fluss.py
docs/api_reference/segmentation.rst

This implements the FLUSS [1] segmenter.
[1] Gharghabi S, Ding Y, Yeh C-CM, Kamgar K, Ulanova L, Keogh E. Matrix
Profile VIII: Domain Agnostic Online Semantic Segmentation at Superhuman Performance
Levels. In: 2017 IEEE International Conference on Data Mining (ICDM). IEEE; 2017.
p. 117-26.
Uses a soft-dependency to stumpy

[ENH] Add FLUSS segmenter from stumpy

---

docs/mentoring.md

[DOC] Fixed a typo in mentoring.md

---

.github/workflows/pr_precommit.yml

Reapplies #1662 since there are still failures on forks for this workflow.

[MNT] Change `pre-commit` workflow checkout ref

---

aeon/anomaly_detection/_merlin.py
aeon/datasets/_data_writers.py

Reference #1705 
Adds reference to docstring for MERLIN anomaly detection
No

[DOC] added reference to docstring of MERLIN anomaly detection

---

aeon/transformations/impute.py
aeon/transformations/lag.py
aeon/transformations/outlier_detection.py
aeon/transformations/summarize.py

deprecate
some may be worth converting.

[DEP] dep fest2

---

aeon/transformations/detrend/_deseasonalize.py
aeon/transformations/detrend/_detrend.py
aeon/transformations/hierarchical/aggregate.py
aeon/transformations/hierarchical/reconcile.py
aeon/transformations/outlier_detection.py

deprecates as part of #1446 and #1611
hierarchical/aggregate.py: Aggregator
hierarchical/reconcile.py: Reconciler
detrend/_deseasonalize.py: Deseasonalizer, ConditionalDeseasonalizer, STLTransformer
detrend/_detrend.py: Detrender

[DEP] dep fest3

---

pyproject.toml

[MNT] Set `keras` bound to fix CI

---

aeon/transformations/collection/pad.py

fixes #1749 by introducing a fit_values_ variable.
this will clash with #1737 but I would like this in and #1737 might take a while to approve ...

[BUG] fix padder fit_values

---

examples/classification/convolution_based.ipynb

[DOC] typo in convolutions notebook

---

.github/workflows/pr_precommit.yml
README.md
aeon/__init__.py
aeon/classification/convolution_based/_arsenal.py
aeon/classification/convolution_based/_hydra.py
aeon/classification/convolution_based/_mr_hydra.py
aeon/classification/convolution_based/_rocket_classifier.py
aeon/classification/dictionary_based/_muse.py
aeon/classification/dictionary_based/_weasel.py
aeon/classification/dictionary_based/_weasel_v2.py
aeon/classification/interval_based/_quant.py
aeon/classification/shapelet_based/_rdst.py
build_tools/pr_labeler.py
docs/changelog.md
docs/changelogs/v0.10.md
pyproject.toml

Release actions for v0.10.0.
A couple of fixes for workflow issues I noticed while generating the changelog.
While discussing multi-threading I noticed a few of the `class_weight` changes had a few documentation inconsistencies, included those here as well.

Release v0.10.0

---

aeon/networks/_ae_bgru.py

[BUG] Fix config of AEBiGRUNetwork from encoder to auto-encoder

---

aeon/classification/dictionary_based/_tde.py
aeon/classification/hybrid/tests/test_hc.py

changes a test that might cause #1726 and changes a test >= to >

[ENH] Change HC2 test to balance class

---

aeon/datasets/_data_writers.py

Fixes #1578 
Removed incomplete line from `write_to_tsfile` in docs.

[DOC] Removed incomplete line from write_to_tsfile

---

pyproject.toml

[MNT] Raise `numba` version bound

---

aeon/networks/__init__.py
aeon/networks/base.py
aeon/networks/tests/test_all_networks.py
docs/api_reference/networks.rst
examples/base/base_classes.ipynb

[DEP] Remove old class base deep network

---

aeon/transformations/collection/dictionary_based/_sfa.py
aeon/transformations/collection/dictionary_based/_sfa_fast.py

minor fix in SFA documentation

[DOC] DFT instead of PAA in SFA docstring

---

aeon/forecasting/compose/tests/test_pipeline.py
aeon/transformations/_legacy/outlier_detection.py
docs/api_reference/transformations.rst

[DEP] Move HampelFilter to legacy

---

aeon/networks/_encoder.py

Fixes #1868.
Remove the tensorflow-addons dependency.
No.
No.

[MNT] Remove tensorflow-addons dependency

---

docs/contributing.md

Fixes #1858
Updates usage information for the issue auto-assign bot

[DOC] Correct info for issue assign bot

---

aeon/classification/convolution_based/_arsenal.py

Fixes #1885
Replace previous citation with the citation from springer : https://link.springer.com/article/10.1007/s10994-021-06057-9#citeas
No.
No.
No.
@all-contributors add @Cyril-Meyer for doc

[DOC] Update paper referenced in Arsenal docs

---

aeon/distances/_ddtw.py
docs/api_reference/distances.rst

Fixes #1720
Add Derivative Dynamic Time Warping (DDTW) to distances modules doc.
No.
No.

[DOC] Add ddtw distance to the API references

---

aeon/classification/shapelet_based/_sast.py
aeon/transformations/collection/shapelet_based/_sast.py

Quick small PR request by Tony in the intern meeting to fix a class tag.

[DOC] Correct sast tags to shapelet

---

aeon/distances/_shape_dtw.py

padding is used in the wrong place for pairwise shapedtw distance

[BUG] Fix bug in shape dtw pairwise function

---

aeon/visualisation/distances/__init__.py
aeon/visualisation/distances/_pairwise_distance_matrix.py

- Part of #1654.
- Simplifies #https://github.com/aeon-toolkit/aeon-tutorials/pull/11.
Implements a new plot that embeds a heatmap with the distances and path between two time series A and B. 
When the time series are short, the plot shows the exact distances between both time series. In case of longer time series (more than 15 timesteps), the cbar is preferred, as exact distances overlap. 
Some examples are:
Small time series (shorter than 15 timesteps):
Medium-sized time series:
Long time series:
None
Some enhancements should be done:
- Doc the function. 
- Work with unequal length time series. 
- Include some restrictions, such as types. 
- Include tests.
- ...

[ENH] Plot the pairwise distance between two time series

---

README.md
aeon/__init__.py
docs/changelog.md
docs/changelogs/v0.11.md
pyproject.toml

Release v0.11.0 

---

aeon/regression/interval_based/__init__.py
aeon/regression/interval_based/_quant.py

Conversion of the `QUANTClassifier` for regression.

[ENH] QUANT regressor

---

aeon/transformations/series/_bkfilter.py

Fixes #1968
Fix error in documentation, see related issue.
No.
I did not check the `_transform` method implementation, just see that the data coming through is not as supposed in the documentation, due to preprocess in base class.
Found while working on #1967.

[DOC] fix BKFilter._transform parameters docs

---

.all-contributorsrc
aeon/anomaly_detection/__init__.py
aeon/anomaly_detection/_stomp.py
aeon/anomaly_detection/tests/test_stomp.py
docs/api_reference/anomaly_detection.rst

Fixes #1638 
Adds the STOMP algorithm for anomaly detection.

[ENH] Add STOMP anomaly detector.

---

README.md
aeon/__init__.py
aeon/similarity_search/base.py
docs/changelog.md
docs/changelogs/v0.11.md
pyproject.toml

Release v0.11.1

---

docs/about/core_developers.md
docs/about/finance_workgroup.md

Adds new developers to the documentation and updates Davids name to match his GitHub profile.

[DOC] Update developer list

---

examples/classification/dictionary_based.ipynb
examples/clustering/partitional_clustering.ipynb

Fixes a few notebook failures caught on the overnight testing.

[DOC] Fix notebook failures

---

aeon/anomaly_detection/_dwt_mlead.py
aeon/anomaly_detection/_pyodadapter.py
aeon/anomaly_detection/_stomp.py
aeon/testing/testing_config.py

Related to #2086
- Fixes the estimator contract for
- DWT_MLEAD
- PyODAdapter
- STOMP
no

[BUG] Fix anomaly detector's compliance with estimator API (related to testing revamp)

---

aeon/classification/dictionary_based/_muse.py
aeon/classification/dictionary_based/tests/test_muse.py

sets MUSE capability:univariate to False, and adds a test to improve coverage.

[ENH] Add MUSE tests

---

aeon/classification/dictionary_based/tests/test_boss.py

single line of coverage for BOSS

[ENH] Add BOSS tests

---

aeon/classification/dictionary_based/tests/test_tde.py
aeon/classification/ordinal_classification/_ordinal_tde.py
aeon/classification/ordinal_classification/tests/__init__.py
aeon/classification/ordinal_classification/tests/test_ordinal_tde.py

fixes #2143 by removing a duplicate function, adds similar tests to #2144

[ENH] Tests for ordinal tde

---

.github/workflows/pr_examples.yml
.github/workflows/pr_pytest.yml

Missed a ! so the label is inverted, oops!

[MNT] Fix numba function caching the PR testing

---

.all-contributorsrc

[DOC] Update .all-contributorsrc to add myself as a contributor

---

aeon/anomaly_detection/tests/test_iforest.py
aeon/transformations/collection/shapelet_based/_dilated_shapelet_transform.py
aeon/utils/numba/general.py

replaces np.float_ with np.float64

[ENH] more fixes for float_

---

aeon/classification/ordinal_classification/tests/test_ordinal_tde.py

closes #926 
adds a few more lines of coverage, enough to close this specific issue imo

[ENH] OrdinalTDE coverage

---

aeon/transformations/collection/_acf.py

closes #1747 
default lags no n_timepoints/4

[ENH] Change ACF default lags

---

aeon/transformations/series/__init__.py
aeon/transformations/series/_gauss.py
aeon/transformations/series/tests/test_gauss.py
docs/api_reference/transformations.rst

Implement Gaussian filter asked in #1920 (which is now fully completed).
Add a new transformation, named `GaussSeriesTransformer` which use [SciPy gaussian_filter1d](https://docs.scipy.org/doc/scipy/reference/generated/scipy.ndimage.gaussian_filter1d.html)
No, but we add another SciPy usage.
Code is based on previous work `DFTSeriesTransformer`. I don't think I've forgotten anything, but there may still be references to the DFT as I started by copying _dft.py and test_dft.py.

[ENH] Gaussian Filter Transformer

---

examples/transformations/rocket.ipynb
examples/transformations/sast.ipynb

Commit 548dd73153a6277d456b0ae1bd8fb545d74385de moved the location of `classification.ipynb`. This PR adjusts sources to changes.

[DOC] Update classification notebook reference

---

aeon/base/_base_collection.py
aeon/utils/validation/collection.py

Fixes #2277 
`aeon.utils.registry.COLLECTIONS_DATA_TYPES` to `aeon.utils.COLLECTIONS_DATA_TYPES`

[DOC]removed registry

---

aeon/transformations/collection/__init__.py
examples/transformations/transformations.ipynb

Fixes #2268 
Fixes #1840 
adds a basic notebook for transformations

[DOC] Add transformations notebook

---

aeon/clustering/base.py

Part of #1530 action from dev meeting on 25/10/24

[ENH] Remove y from predict in BaseClusterer

---

aeon/regression/deep_learning/_inception_time.py
docs/api_reference/data_format.rst
docs/examples.md
docs/index.md
examples/datasets/data_loading.ipynb
examples/datasets/load_data_from_web.ipynb
examples/distances/sklearn_distances.ipynb
examples/pydata/Amsterdam-2023/Lets_do_the_time_warp_again.ipynb
examples/transformations/minirocket.ipynb
examples/transformations/resizing.ipynb

fixes #2107 
at least the ones I found.

[DOC] Fix broken links

---

aeon/classification/shapelet_based/_ls.py
aeon/classification/shapelet_based/tests/test_ls.py
aeon/testing/expected_results/expected_classifier_outputs.py

taking up a fair chunk of test time, try making it smaller in tests

[ENH] Change test set up for LearnedShapelets

---

aeon/utils/validation/series.py
aeon/utils/validation/tests/test_series.py
aeon/visualisation/estimator/_clasp.py
aeon/visualisation/learning_task/_forecasting.py
aeon/visualisation/learning_task/_segmentation.py

small bushfire for KWF broke out in utils/validation. This PR removers a lot of legacy code not used anywhere and all related to redundant checks

[ENH] remove old check_series and other legacy functions

---

aeon/utils/show_versions.py

[ENH] show versions option to print

---

.all-contributorsrc
CODEOWNERS
aeon/anomaly_detection/_dwt_mlead.py
aeon/anomaly_detection/_kmeans.py
aeon/anomaly_detection/_pyodadapter.py
aeon/anomaly_detection/_stomp.py
aeon/anomaly_detection/tests/test_dwt_mlead.py
aeon/anomaly_detection/tests/test_kmeans.py
aeon/anomaly_detection/tests/test_pyod_adapter.py
aeon/anomaly_detection/tests/test_stomp.py
aeon/distances/_sbd.py
aeon/performance_metrics/anomaly_detection/_binary.py
aeon/performance_metrics/anomaly_detection/_continuous.py
aeon/performance_metrics/anomaly_detection/_util.py
aeon/performance_metrics/anomaly_detection/_vus_metrics.py
aeon/performance_metrics/anomaly_detection/thresholding.py
aeon/utils/windowing.py
docs/about/core_developers.md
docs/changelogs/v0.10.md
docs/changelogs/v0.11.md
docs/changelogs/v0.7.md
docs/changelogs/v0.8.md
docs/changelogs/v0.9.md

I updated my GitHub username from CodeLionX to SebastianSchmidl. This fixes all the references in the aeon documentation and in the CODEOWNERS-file.
The `CONTRIBUTERS.md`-file is automatically updated, right?

[MNT] Updated username

---

aeon/classification/deep_learning/__init__.py
aeon/classification/deep_learning/_cnn.py
aeon/classification/deep_learning/_disjoint_cnn.py
aeon/classification/deep_learning/_encoder.py
aeon/classification/deep_learning/_fcn.py
aeon/classification/deep_learning/_inception_time.py
aeon/classification/deep_learning/_lite_time.py
aeon/classification/deep_learning/_mlp.py
aeon/classification/deep_learning/_resnet.py
aeon/networks/__init__.py
aeon/networks/_disjoint_cnn.py
aeon/networks/_mlp.py
aeon/networks/tests/test_all_networks.py
aeon/networks/tests/test_disjoint_cnn.py
aeon/regression/deep_learning/__init__.py
aeon/regression/deep_learning/_cnn.py
aeon/regression/deep_learning/_disjoint_cnn.py
aeon/regression/deep_learning/_encoder.py
aeon/regression/deep_learning/_inception_time.py
aeon/regression/deep_learning/_lite_time.py
aeon/regression/deep_learning/_mlp.py
aeon/regression/deep_learning/_resnet.py
docs/api_reference/classification.rst
docs/api_reference/networks.rst
docs/api_reference/regression.rst

Fixes #1902 
Check list:
Also doing a huge refactor on docs for deep learning while at it, old flaw in docstrings fixed now

[ENH] Add DisjointCNN classifier and Regressor

---

aeon/transformations/collection/__init__.py
aeon/transformations/collection/_impute.py
aeon/transformations/collection/tests/test_simple_imputer.py
docs/api_reference/transformations.rst

Fixes #2293 
Implements `SimpleImputer` class in `aeon.transformations.collections`, along with test cases.

[ENH] Implemented SimpleImputer

---

examples/transformations/preprocessing.ipynb

adds our new SimpleImputer (thanks @notaryanramani ) to the preprocessing notebook.

[DOC] Add imputer to notebook

---

aeon/anomaly_detection/_lof.py

Fixes the CI run for `main`.
- adds the `capability:multithreading` tag to `LOF`
no

[BUG] add multithreading capability tag to LOF to fix main

---

docs/api_reference/networks.rst

[DOC] Update api references of networks

---

.github/workflows/fast_release.yml
.github/workflows/issue_assigned.yml
.github/workflows/issue_comment_edited.yml
.github/workflows/issue_comment_posted.yml
.github/workflows/periodic_github_maintenace.yml
.github/workflows/periodic_tests.yml
.github/workflows/pr_core_dep_import.yml
.github/workflows/pr_examples.yml
.github/workflows/pr_opened.yml
.github/workflows/pr_precommit.yml
.github/workflows/pr_pytest.yml
.github/workflows/pr_typecheck.yml
.github/workflows/precommit_autoupdate.yml
.github/workflows/release.yml
.github/workflows/scorecard.yml
.github/workflows/update_contributors.yml
.readthedocs.yml

Currently failing on main and release, but not periodic tests.

[MNT] Trying to diagnose ubuntu workflow failures

---

aeon/forecasting/_ets.py
aeon/forecasting/tests/test_base.py
aeon/forecasting/tests/test_ets.py
aeon/forecasting/tests/test_regressor.py

should be 100% coverage for base and regressor, slight restructuring of ETS means still some coverage required, but will do it in a later PR

[ENh] Forecasting tests

---

aeon/distances/elastic/_ddtw.py

Closes #2442 
Fixes parenthesis mismatch & referencing issue.

[DOC] ddtw_distance Documentation Fix

---

README.md

adds a line to the readme at the end

[DOC] Add comment to readme.md

---

aeon/transformations/collection/imbalance/__init__.py
aeon/transformations/collection/imbalance/_adasyn.py
aeon/transformations/collection/imbalance/_smote.py
aeon/transformations/collection/tests/test_imbalance.py

ongoing, part of https://github.com/aeon-toolkit/aeon/issues/2412
Reimplement SMOTE/ADASYM or use imbalanced-learn version

[ENH] wrapper for smote and adasyn of the imbalance module in collection transformers

---

aeon/classification/convolution_based/_arsenal.py
aeon/classification/convolution_based/_hydra.py
aeon/classification/convolution_based/_minirocket.py
aeon/classification/convolution_based/_mr_hydra.py
aeon/classification/convolution_based/_multirocket.py
aeon/classification/convolution_based/_rocket.py

Fixes #1454
All the .py files in the "/aeon/classification/convolution_based" module were missing type hints for primitive and string data types. I have added the necessary type hints for the module.
No
No

[DOC] added type hints to 'classification->convolution_based' module

---

aeon/classification/deep_learning/_lite_time.py
aeon/networks/_lite.py
aeon/regression/deep_learning/_lite_time.py

Fixes #1867 
Removes the list from the documentation of LITE Network in deep learning of regression classification and networks
No

[BUG] LITE Network : Fixed list arguments

---

aeon/anomaly_detection/_pyodadapter.py
docs/developer_guide.md
docs/developer_guide/adding_typehints.md
docs/developer_guide/documentation.md

Closes #1857
Tidies up the type hint guide a bit and adds a link to it from the developer guide page.

[DOC] Improve type hint guide and add link to the page.

---

.github/workflows/pr_core_dep_import.yml
.github/workflows/pr_examples.yml
.github/workflows/pr_precommit.yml
.github/workflows/pr_pytest.yml
.github/workflows/pr_typecheck.yml

I don't think restricting this to main is necessary. Knowing whether a PR if going to break any branch is useful.

[MNT] Run PR tests when merging on any branch

---

aeon/forecasting/__init__.py
aeon/forecasting/_naive.py
aeon/forecasting/base.py
aeon/forecasting/tests/test_base.py
examples/forecasting/forecasting.ipynb

simple refactor, part of https://github.com/aeon-toolkit/aeon/issues/2823

[ENH] refactor dummy forecaster to naive

---

aeon/benchmarking/results_loaders.py
aeon/benchmarking/tests/test_results_loaders.py

#2879 
switch loaders to https, may fix this bug
no

[BUG] Switch results loaders from http to https

---

.github/utilities/pr_open_commenter.py

Changes the message posted on new PRs. Removes the broken latex coloring, this does not render on mobile correctly anyway and it now broken on desktop as well.
Puts the PR labelling options in a drop down box as they are not relevant to most contributors and take up space.

[MNT] PR open bot comment changes

---

aeon/forecasting/base.py
aeon/forecasting/tests/test_base.py

seems safer to clone it, and ran into a need to do so in TVPRegressor
once #2927 is in I will move the test of equiv output to the test suite

[ENH] Clone estimator in direct forecast

---

aeon/transformations/collection/dictionary_based/_sax.py

Fixes #2873
add n_jobs parameter and use check n_jobs with set num threads to set it for the parallel numba function for sax invertion.

[MNT] add n_jobs parameter for sax invertion

---

docs/api_reference/classification.rst
docs/api_reference/transformations.md

also change DummyClassifier API to match clustering and regression

[DOC] Add Imbalance transformers to API

---

.github/utilities/generate_developer_tables.py
.github/utilities/issue_assign.py
.github/utilities/remove_good_first_issue.py
.github/workflows/weekly_github_maintenance.yml
.pre-commit-config.yaml
docs/about/supporting_developers.md

A few fixes for workflows and updates the team tables.

[MNT] Workflow maintenance and dev table update

---

aeon/forecasting/_naive.py
aeon/forecasting/_regression.py
aeon/forecasting/base.py
aeon/forecasting/stats/_ets.py
aeon/forecasting/stats/_tvp.py
aeon/forecasting/stats/tests/test_ets.py
aeon/forecasting/tests/test_base.py
aeon/forecasting/tests/test_naive.py
aeon/testing/estimator_checking/_yield_forecasting_checks.py

Converts the different multi-output forecasting methods into mixins.
Adds more checks in the base class.
Remove `_fit` for naive

[ENH] Forecasing mixins and base class checking

---

aeon/networks/_tcn.py
aeon/networks/tests/test_tcn.py

The network had issues in docstrings flipping channels and time axes. Also the last step was taking the last channel not the last time stamp

[BUG] Issue with axis in `TCNNetwork`

---

pyproject.toml

Caused by an update to our test rerun plugin. Removed for now.

[MNT] Fix CI failures

---

docs/api_reference/forecasting.rst
docs/api_reference/networks.rst

added TCN and DeepAR networks into networks api as well as BaseDeepForecaster and TCNForecaster to forecasting api

[DOC] Update api references for Deep Forecasters
