sktime/classification/dictionary_based/_boss.py
sktime/classification/dictionary_based/_cboss.py
sktime/classification/dictionary_based/_weasel.py
sktime/classification/dictionary_based/tests/test_boss.py
sktime/transformations/panel/dictionary_based/_sfa_fast.py

Maintenance of Dictionary Classifiers
- Reverts `alphabet_size=4` for BOSS and WEASEL, 
- carries out deprecation of CBOSS
- adds dilation to SFAFast
- Tidies up Doc-Strings

[ENH] Dictionary Classifiers

---

.pre-commit-config.yaml

I'm removing `shellcheck` from precommit check since it causes problems when a python version is not compiled with a bunch of optional modules. This is a frustration when working with python from `pyenv` since shellcheck itself fails requiring `readlines`.
Shellcheck is only linting/checking shell scripts and there a few of those that almost never change and are rarely used so it is not critical.
NO

[MNT] remove shellcheck from pre-commit checks

---

.all-contributorsrc
sktime/classification/distance_based/_time_series_neighbors.py
sktime/classification/distance_based/tests/test_time_series_neighbors.py
sktime/regression/distance_based/_time_series_neighbors.py
sktime/regression/distance_based/tests/test_time_series_neighbors.py

- Fixes #39.
- Reimplemented both `KNeighborsTimeSeriesClassifier` and `KNeighborsTimeSeriesRegressor` in order to fix memory leaks and replace hard coded "distances" string list.
- Removed computation of distance matrices in `fit` (which was useless in any case) and `predict`, as well as `sklearn`'s `KNeighbors` instances contained within the models. The k-Neighbors algorithm is now implemented here.
- Nearest neighbors are found by `np.argpartition`ing the distance vector into `[0..k-1]`, `[k]`, `[k+1..]`, which is $O(n)$ as opposed to the $O(n \log n)$ in sorting.
- Distance metrics are now generated by `distance_factory`, uncoupling the selection of possible metrics from the model.
The following graphs show the results of current and new implementation benchmarks. The experiments were …

[ENH] kNN Classifier and Regressor reimplementations

---

.all-contributorsrc
sktime/classification/tests/test_base.py

[BUG] Remove duplicate function in classification/tests/test_base.py #119
Fixes #119 [BUG] Remove duplicate function in classification/tests/test_base.py 
Removed a duplicate function inside classification/tests/test_base.py
No

Remove duplicate function 

---

sktime/annotation/eagglo.py
sktime/annotation/tests/test_eagglo.py

This PR improves the runtime of EAgglo by a factor of 5-10, by use of:
- NUMBA
- Reimplement Euclidean Distance (instead of scipy cdist)
- Reworked initial distance computations, if `self._member is None` (no groupings + Pandas needed)
```python
from sktime.datasets import load_gun_point_segmentation
ts, period_size, cps = load_gun_point_segmentation()
model = EAgglo(penalty=lambda x: np.mean(np.diff(np.sort(ts))))
fitted_model = model._fit(pd.DataFrame(ts[:2000]))
```

[ENH] Speedup EAgglo by factor 5-10x

---

sktime/registry/__init__.py
sktime/registry/_base_classes.py
sktime/registry/_lookup.py
sktime/registry/tests/test_lookup.py
sktime/tests/_config.py
sktime/tests/test_all_estimators.py
sktime/transformations/base.py
sktime/transformations/panel/compose.py
sktime/utils/_testing/scenarios_transformers.py

A bit of clean-up in preparation for #149.
The only usage is `ColumnTransformer` which is very outdated and requires a rework. I have added it to the text exclude list.

[ENH] Remove old Transformer Minxin Classes

---

pyproject.toml

The issue is fixed in https://github.com/plotly/dash/pull/2461, but a new release is required to fix our CI.

[MNT] Fix pytest by setting upper bound on `dash`

---

aeon/classification/deep_learning/inception_time.py

Fixes #193 
Added the deep  learning algorithm name tag to inceptionTime classifier given that he inherits from BaseClassifier and not BaseDeepClassifier
No

[BUG] added missing dl tag to inceptionTime classifier

---

aeon/classification/compose/tests/test_ensemble.py
aeon/classification/early_classification/tests/test_all_early_classifiers.py
setup.cfg

this removes a couple of calls to iloc for returned data that is no longer a data frame. It also removes a test that is skipped and listed as being deprecated some time ago.

[ENH] remove incorrect iloc calls

---

aeon/transformations/panel/dictionary_based/tests/test_sfa.py

Sporadic failure of test_sfa (tests a private method of sfa) caused by random class values occasionally being all the same value fixed by hard coding the testing class values to be evenly balanced
Fixes #223

[BUG] fix class values for SFA tests

---

aeon/transformations/tests/test_all_transformers.py

this PR simply removes the Transformer test function 
test_fit_transform_output
this function, added in April 2022, imposes the twisted input/output matching of the Panel/Series/Table/Primitive restriction on what transformers can return based on their input. It is not needed imo, but it is also deeply flawed. For example if I want to transform series to series, if I input 3D numpy, it will not let me return 3D numpy, whether I set the tags to "Series" or "Panel" . Digging down, it is, as usual, riddled with exceptions and special cases. For example, at the heart is this
```python
def check_is_scitype(
obj,
scitype: Union[str, List[str]],
return_metadata=False,
var_name="obj",
exclude_mtypes=AMBIGUOUS_MTYPES,
):
```
which is deeply hidden in registry 
```python
AMBIGUOUS_MTYPES = …
```

[ENH] remove test_fit_transform_output

---

aeon/transformations/series/impute.py

The Imputer transform begins by allowing the user to specify what value represents missing. 
if self.missing_values:
X = X.replace(to_replace=self.missing_values, value=np.nan)
python interprets 0 as False in a C style. This corrects that to 
if self.missing_values is not None:
X = X.replace(to_replace=self.missing_values, value=np.nan)
Fixes #266

[ENH] change Imputer to allow for 0 to be the missing value to replace

---

pyproject.toml

We use `packaging` for soft dependencies, but it is not included as a dependency itself. There have been some people missing it when they install `aeon`.
Fixes #55 
Fixes #256

[BUG] Include `packaging` as a dependency

---

aeon/clustering/base.py
aeon/clustering/tests/test_k_means.py

removes all mention of the soon to be deprecated "nested_univ" data type, only actual change is to test that called head, rest is docstrings
#110

[ENH] remove clustering mentions of nested_univ

---

aeon/tests/_config.py
aeon/tests/test_all_estimators.py
setup.cfg

test_all_estimators calls fit a very large number of times. Whislt I appreciate having clear tests that do things independently, the state of testing is so slow, I think its worth combining some of them to reduce the calls to fit. 
test_returns_self takes about a minute and calls fit on everything, testing if self is returned. I have rolled this into test_fit_updates_state, using the call to fit there to test self and to print the same error message. This takes it locally down from 13mins 6 sec to 11m 43s (not including loading). Every little helps!
there are other similar compromises we could make here to reduce the number of fit calls. Real pig is forecasting though, need to address that at some point

[ENH] combine test_returns_self with test_fit_updates_state

---

aeon/transformations/panel/dwt.py
aeon/transformations/panel/tests/test_dwt.py

and another one, doing them one PR at a time to avoid big PRs. This could be made faster with numba I'm sure. Like PAA, it does the weird reshape to allow for channel-wise transform, simply to conform to existing code. This could also possibly be done better. 
Reference Issues/PRs
fixws #98 
part of #197 #110

[ENH] Convert DWTTransformer to use numpy format internally

---

aeon/forecasting/compose/tests/test_reduce_global.py
aeon/forecasting/model_selection/tests/test_tune.py
aeon/forecasting/tests/_config.py
aeon/forecasting/tests/test_all_forecasters.py
aeon/utils/_testing/series.py

- drop parametrization over random seeds
- update
- drop the redundant test_predict_time_index
- unparametrize test_equality_transfo_nontranso test
- related #154 
Dropping `test_predict_time_index` is based on the observation that is essentially tests the `ForecastingHorizon` scenarios since all forecasters should inherit from `BaseForecaster` and therefore the use `check_fh` in `fit` which converts whatever input into a `ForecastingHorizon` instance. Tests for different inputs to `ForecastingHorizon` are already covered by `test_fh` so `test_predict_time_index` is redundant here.
Some timings from my local env:
- with `test_predict_time_index`: 12844 passed, 351 skipped, 117 warnings in 2019.45s (0:33:39)
- wthout`test_predict_time_index`: - 10900 passed, 351 skipped, 117 warnings in …

[MNT] Cleanup the forecasting tests

---

aeon/classification/_dummy.py
aeon/classification/base.py
aeon/classification/compose/_channel_ensemble.py
aeon/classification/deep_learning/inception_time.py
aeon/classification/dictionary_based/_muse.py
aeon/classification/distance_based/_shape_dtw.py
aeon/classification/early_classification/base.py
aeon/classification/feature_based/_signature_classifier.py
aeon/classification/sklearn/_rotation_forest.py
aeon/classification/tests/_classification_test_reproduction.py
aeon/classification/tests/test_base.py
aeon/regression/deep_learning/inception_time.py
setup.cfg

This removes the nested_univ from ShapeDTW (also fixes a couple of bugs I found there with "compound" option) and also removes doc string mentions to using nested Pandas dataframes. There is no usage of the nested_univ input type in classification, regression or clustering. There are still some transformations to do, and some testing to revise
Part of #110

[ENH] Removes nested dataframes from shape dtw

---

docs/get_involved.rst
docs/index.md

The meetups page no longer exists, and the sponsor buttons links to some random open collective (https://opencollective.com/aeon)

[DOC] Remove meetup and sponsor cards from get involved

---

aeon/utils/_maint/_show_versions.py

Fixes #343. 
Calling the `show_versions` function caused an assertion error. The cause was in the `_get_deps_info` function. Apparently, importing `pip` before `setuptools` caused some kind of version incompatibility due to `setuptools` completely replacing `distutils` in 3.11.
The error was fixed by updating the module importing code, making it more similar to the current `sklearn.show_versions` function.
No.
Not needed.

[BUG] Fixes `show_versions` error

---

aeon/datasets/_single_problem_loaders.py

Fixes #342.
The function `load_covid_3month` is now correctly converting its `y` array (or `class_val` column in case `return_X_y=False`) to floats.
No.
Since the single problem loaders cover a wide variety of problem types (classification, forecasting and now regression), each with different types of data formats, I believe the individual `load_****` functions could and should do work on their own, instead of only being wrappers to `_load_dataset`. However, other, more impactful ways of addressing this issue are possible, such as having `_load_classification_dataset` , `_load_regression_dataset`,  and `_load_forecasting_dataset`  functions instead of a single catch-all `_load_dataset`.
If the maintainers would prefer that approach, I'd be happy to work on it.
No.

[BUG] Fixes `load_covid_3month` returning a non-numeric `y`

---

aeon/classification/base.py
aeon/classification/dictionary_based/_weasel_v2.py
aeon/classification/distance_based/_time_series_neighbors.py
aeon/classification/early_classification/base.py
aeon/classification/sklearn/_rotation_forest.py
aeon/classification/tests/test_sklearn_compatability.py
aeon/regression/base.py
aeon/regression/distance_based/_time_series_neighbors.py

Part of #42 
Purely cosmetic PR removes mentions of the term Panel from classification, clustering and regression which to machine learning people  has no meaning at all. mtype generally changed to input type. Left the pipelines alone, they are of marginal use. Not changed any code, conversion and checking changes comes later.

[ENH] purge mentions of Panel in classification

---

.all-contributorsrc

Project owner in `.all-contributorsrc` is set to `aeon`, making the emojis in `CONTRIBUTORS.md` incorrectly link to `https://github.com/aeon/aeon/...`, which causes a 404.
I've changed it to `aeon-toolkit`.

[MNT] Changes repo owner to aeon-toolkit in `.all-contributorsrc`

---

.all-contributorsrc
docs/contributors.md

Adds an image from [contrib.rocks](https://contrib.rocks) to the webpage and reduces the amount of columns and image size used by all-contributors to give each table item a bit more space.
There have been issues previously regarding displaying contributors decided via vote, but I don't feel the suggestions are feasible. https://github.com/sktime/sktime/issues/3716 seems to be defunct now, and https://github.com/sktime/sktime/issues/3717 would take an enormous amount of effort to implement and maintain.

[DOC] Add contrib.rocks image to `contributors.md` and lower all-contributors table/image size

---

docs/api_reference/datasets.rst
docs/api_reference/regression.rst

removes mentions in the api_reference to deprecated function and regressor

[MNT] docs update to fix readthedocs fail

---

aeon/datatypes/_panel/_convert.py
aeon/transformations/panel/tsfresh.py

Fixes #381 
The fix is simply to assign column/channel names of the format "dim_X" in the conversion of long format. I have also turned off the warnings by default, because it is generating 100s of lines of nonsense. If anyone really wants them, I'll put them back.

[BUG] fix tsfresh "kind" feature extractor 

---

aeon/transformations/panel/summarize/_extract.py
aeon/transformations/panel/summarize/tests/test_RandomIntervalFeatureExtractor.py

part of #197 
Adapts PlateauFinder to use numpy3D. I have done this in the minimal way possible, so it still returns data in the same format. This is for backward compatibility, and this is not transformer used anywhere else in the package.

[ENH] Adapt PlateauFinder to use numpy3D

---

aeon/registry/_lookup.py
aeon/registry/tests/test_lookup.py

Fixes #182 
The bug in #182 was caused by all_estimators not handling the case when a tag can have multiple values. So, for example, to handle multiple possible input types, the dummy classifier
"X_inner_mtype": ["np-list", "numpy3D"],
we have inherited all this, but it allows classifiers to handle both equal and unequal length, and all_estimators as a tag filter is useful. However, all_estimators assumes that the result of a call of (for example)
estimator.get_class_tag("X_inner_type") 
returns a string, rather than a list. This just adds a test of whether a list is returned and acts accordingly. This example
```python
from aeon.registry import all_estimators
f4=all_estimators("classifier",filter_tags={"X_inner_mtype": "np-list"})
print(f4)
```
now returns the only classifier currently …

[BUG] fix all_estimators to work with tags that are lists of strings not just single strings

---

aeon/transformations/panel/interpolate.py
aeon/transformations/panel/tests/test_interpolate.py

part of #197 
Converts TSInterpolator to use numpy3D or np-list interchangeably. 
1. Note I would like to change the name of this transformer to Interpolator, but will do that at another time. 
2. I have switched from using scipy.interpolate1D to use np. iterp because it is both simpler and faster. 
3. I have also added an example and simplified the test

[ENH] convert TSInterpolator to np-list/numpy3D

---

aeon/tests/_config.py
aeon/tests/test_all_estimators.py

see 
https://github.com/aeon-toolkit/aeon/issues/271
https://github.com/aeon-toolkit/aeon/issues/347
The deep learning algorithms are fundamentally not deterministic. They also cannot be pickled. There are three relevant tests in test_all_estimators
"test_fit_idempotent",
"test_persistence_via_pickle" 
"test_save_estimators_to_file",
firstly, I have refactored the poorly named test_fit_idempotent to test_fit_deterministic. I have then escaped tests if the estimator is a DeepClassifier or DeepRegressor. Turns out this is done all over the testing. Currently, InceptionTime is still excluded because technically it is an ensemble of deep learners, not a deep learner itself.

[EN] Hard code deep learning exclusions from tests

---

docs/getting_started.md

Slight rewrite of the data section to introduce topics sequentially in #393.
Also adds back the line "See [here](/examples/datasets/AA_datatypes_and_datasets.ipynb) for more information on input datatypes." to the top of the page.

[DOC] Changes to #393

---

aeon/classification/compose/tests/test_pipeline.py
aeon/classification/distance_based/_time_series_neighbors.py
aeon/registry/_tags.py
setup.cfg

Part of #408 
this adds  unequal length capability to KNN. This is trivial following the distances refactor, I've not written a proper test yet, but this works fine
```python
from aeon.classification.distance_based import KNeighborsTimeSeriesClassifier
from aeon.datasets import load_plaid, load_japanese_vowels
def plaid(cls):
X, y = load_plaid(split="TRAIN")
X = X[:50]
y = y[:50]
X_test, y_test = load_plaid(split="TEST")
X_test = X_test[:50]
y_test = y_test[:50]
cls.fit(X,y)
preds = cls.predict(X_test)
print("PLAID preds = ",preds)
print("score =",cls.score(X_test, y_test))
def jap_vowels(cls):
X, y = load_japanese_vowels(split="TRAIN")
X = X[:50]
y = y[:50]
X_test, y_test = load_japanese_vowels(split="TEST")
X_test = X_test[:50]
y_test = y_test[:50]
cls.fit(X,y)
preds = …
```

[ENH] Allow KNN to take unequal length series. 

---

pyproject.toml

Tests are currently failing due to the recently updated `holidays` dependency of `prophet`. This PR excludes the latest release for now.

[MNT] Set upper bound on `holidays` to fix CI

---

.all-contributorsrc
aeon/utils/sampling.py
aeon/utils/tests/test_sampling.py

Fixes #459.
Makes the `stratified_resample` function work with 3D and 2D numpy arrays, and DataFrames for backwards compatibility.
I've remade the function so that it deals mostly with indexes. This makes the function agnostic (for the most part) to the underlying implementation of `X_train` and `X_test`.
It still, however, can't deal with lists of 2D arrays (such as unequal length datasets). I can easily add that if necessary.

[BUG] Fixes `stratified_resample` so that it works with 3D numpy

---

docs/get_involved/governance.md

An alternative to the current governance roles in #195 inspired by Pandas workgroups. This would replace the currently inherited Community Council (CC) role.
The exact workgroups and details surrounding them are all up for debate.

[GOV] Governance workgroups

---

README.md

The current one is relative and doesnt show up on PyPi

[DOC] Change README logo link

---

aeon/classification/base.py
extension_templates/classification.py
setup.cfg

We have an internal mechanism in base classifier for the edge case when all the y values seen in fit are the same. The predict and predict_proba then just return that value or prob = 1 of that value.
this was done by a call to check_is_scitype, which involves multiple scans of the data. This simplifies it by using len, except for the edge case of using multi index DataFrame. 
Also removed a pointless duplication in tests and moved the overloaded operator to the bottom of the file and changed series_length to n_timepoints.

[REF] change single class use case

---

aeon/transformations/collection/rocket/tests/test_MultiRocketMultivariate.py

Test size for multirocket sometimes exceeds the memory allowance for CI, see
https://github.com/aeon-toolkit/aeon/actions/runs/5392735109/jobs/9791701994?pr=514
this just reduces the size to reduce the memory footprint

[BUG] reduce test size for MultiRocket

---

pyproject.toml

New version has a bug importing `torch` which breaks CI.

[MNT] Set upper bound for `tslearn` to fix CI

---

pyproject.toml

Currently the wheels for the latest version on Windows 3.9 are breaking.

[MNT] Change `esig` dependency version requirements to fix CI

---

pyproject.toml

An update to tensorflow has broken some of the deep learning tests, and numpy 1.24 has broken the kalman filter transformer.

[MNT] Setting more upper bounds to fix CI

---

build_tools/run_examples.sh

The notebook loads data from an external source, so we should not run it in our CI. It is currently failing, but this is for multiple PRs so it may require looking at if it's not an external issue @TonyBagnall.

[MNT] Exclude results loading notebook

---

CODEOWNERS

Suggestions for #547.
- Orders entries by file structure
- Edits top comment
- Removes/fixes a few broken entries i.e. `aeon/transformations/collection/augmenter.py @MrPr3ntice @iljamaurer`
- Adds team wide pings to important docs (dont know if this would work!)
The only change in owners is `aeon/regression/deep_learning @hadifawaz1999 @MatthewMiddlehurst @TonyBagnall`

[MNT] CODEOWNERS organisation suggestion

---

aeon/classification/shapelet_based/_rdst.py

Adds the non-deterministic tag to RDST, due to a bug on MacOS causing tests to fail currently (#324)

[BUG] Add `non-deterministic` tag to RDSTClassifier

---

aeon/clustering/clara.py
aeon/clustering/clarans.py
aeon/clustering/k_medoids.py

the overnight tests run everything without numba so we can properly measure coverage. The cluster examples take ages or time out with DTW, so this simply sets the distance in the examples to euclidean

reduce examples time for clusterers

---

aeon/classification/deep_learning/inception_time.py
aeon/regression/deep_learning/inception_time.py
aeon/tests/_config.py

see #347 
Adds the `non-deterministic` and `cant-pickle` tags used by other deep learners and enables the previous disabled tests. Also adds back the CNNNetwork test.

[MNT] Remove InceptionTime estimators from test exclusion

---

CODEOWNERS
docs/about/core_developers.rst

Adds @dguijo to the About webpage as a core developer and adds them to the CODEOWNERS for regression after the recent core developer vote.
If there are any other changes required/requested just post them here.

[DOC] Add @dguijo to core developer table and CODEOWNERS

---

aeon/annotation/adapters/_pyod.py
aeon/annotation/hmm_learn/gaussian.py
aeon/annotation/hmm_learn/gmm.py
aeon/annotation/hmm_learn/poisson.py
aeon/benchmarking/_critical_difference.py
aeon/clustering/k_shapes.py
aeon/clustering/kernel_k_means.py
aeon/forecasting/arima.py
aeon/forecasting/bats.py
aeon/forecasting/fbprophet.py
aeon/forecasting/statsforecast.py
aeon/forecasting/tbats.py
aeon/forecasting/varmax.py
aeon/networks/cnn.py
aeon/networks/encoder.py
aeon/networks/fcn.py
aeon/networks/inception.py
aeon/networks/mlp.py
aeon/networks/tapnet.py
aeon/transformations/collection/tsfresh.py
aeon/transformations/series/bkfilter.py
aeon/transformations/series/filter.py
aeon/transformations/series/kalman_filter.py
aeon/transformations/series/matrix_profile.py
aeon/utils/mlflow_aeon.py
docs/developer_guide/dependencies.rst
extension_templates/classification.py
extension_templates/forecasting.py
extension_templates/transformer.py
pyproject.toml

Current procedure for soft dependencies is to top a warning when imported if the soft dependency package is missing.
IMO, this does not accomplish much. Either you are directly using the contents of the package and will run into an error because of the missing dependency anyway with the relevant information, or you are indirectly importing the contents while using surrounding functionality in which case the warning is not required.
I think it would remove a lot of output clutter if we remove them. People are welcome to give their thoughts on the current procedure and the usefulness of these warnings.

[ENH] Remove top of file warnings for soft dependencies

---

docs/developer_guide/dev_installation.md
docs/index.md
docs/installation.md

Rewrites the developer install instructions page into a simplified 3 step guide including pre-commit.
Adds some instructions for installing from conda-forge.
Resolves #33

[DOC] Developer and `conda` install instructions 

---

examples/regression/regression.ipynb

Emphasises the notebook more as a TSER notebook, aimed at introducing the `regression` package. Includes a link to the `forecasting_sklearn` notebook for the forecasting alternative.
See #647.

[DOC] Regression notebook update

---

aeon/datasets/_data_loaders.py
setup.cfg

fixes (hopefully) #676 
load_classification/regression/forecasting had a redundant call to os.path.dirname for the extract path, perhaps a legacy of previously passing the file name with the path. This meant this fails
https://gist.github.com/BenGravell/9a0a8257d4fed5f543a721a2ad6d0ee0
removing the call makes no difference I can see, apart from removing the need for the suffix slash

[BUG] remove unnecessary call to os.path.dirname

---

aeon/tests/_config.py
setup.cfg

See #347 
This PR unexcludes
1.     "SeriesToSeriesRowTransformer": ["test_non_state_changing_method_contract"],
no longer exists
2. "Prophet": ":test_hierarchical_with_exogeneous" # Issue fixed by prophet
3.    "SignatureClassifier": [
"test_classifier_on_unit_test_data",
"test_classifier_on_basic_motions",
],
passes test_all_classifiers, may be mac or intermittent?
4. SquaringResiduals": ["test_predict_residuals"],
5. "StackingForecaster": ["test_predict_time_index_with_X"],
6. "WindowSummarizer": ["test_methods_have_no_side_effects"],
7. VARMAX": [
"test_update_predict_single",
"test__y_when_refitting",
all pass locally on test_all_forecasters (1hr 16 mins version), test_all_classifiers and test_all_estimators. This has passed 3 times  on CI
This just leaves the 
1. early classifiers …

[MNT] remove exclusions

---

.all-contributorsrc
.github/workflows/update_contributors.yml

The last update did not automatically create a PR to update `CONTRIBUTORS.md`. I think this was because of a comma at the end of the file.
Updates the file generator to allow newer versions.

[MNT] Update contributors file

---

aeon/classification/tests/test_all_classifiers.py
aeon/utils/_testing/collection.py

Part of #42 
removes two redundant calls to aeon.datatypes

[MNT] Remove calls to aeon.datatypes

---

.github/ISSUE_TEMPLATE/sweep.yml

Adds an issue template for [Sweep](https://github.com/sweepai/sweep/tree/main), which has been enabled in aeon for now (currently testing).
#730 I made an attempt at using the bot here, see how it goes. The prompt may not be the best 🙂.

[MNT] Sweep issue template

---

aeon/annotation/plotting/utils.py

Fixes #747.
@TonyBagnall Issue stems from updating matplotlib.

[Bugfix] Deprecation of tick.label in matplotlib >3.8.0

---

setup.cfg

Some of the config lines for pytest were accidently commented in #760. This uncomments them.

[MNT] Uncomment `pytest` config

---

aeon/datasets/tests/test_data_loaders.py
aeon/distances/tests/test_distances.py
aeon/distances/tests/test_pairwise.py
setup.cfg

shape DTW generates tiny numeric differences on mac, this tests almost equal rather than equal. 
Fixes #790

[BUG] Precision error on dist tests on mac

---

sweep.yaml

Sweep is now posting on each PR using the rules system. This PR adds a couple of new rules.
Could be useful as a reminder to add things like the API docs, and if anyone wants to give the AI a go on their PR good luck to them 🙂 
Depending on the results some of these may be removed or tweaked.

[MNT] Add new `sweep` rules and make current rules more specific

---

.github/workflows/pr_opened.yml
aeon/classification/deep_learning/inception_time.py
aeon/transformations/collection/catch22.py
build_tools/pr_labeler.py
build_tools/pr_open_commenter.py

This PR adds a workflow and scripts to automatically label PRs based on the title and contents changed. This is similar to how `scikit-learn` does some of their labelling. 
[MNT] in the title should add the maintenance labels, [MNT,GOV] maintenance and governance lablels, etc.
Changes to the classification package should add classification, transformations the transformations label, examples the examples label etc. If this would add more than 3 labels, none are added to reduce bloat.
The actions will (should) post the changes made and a welcoming comment on the PR when it is opened.
I have made two uncontroversial (I hope) doc string changes to demonstrate this.

[MNT] Add auto label and welcoming comment workflow for PRs 

---

.github/workflows/precommit_autoupdate.yml

This workflow will automatically update the `pre-commit` hooks in .pre-commit-config.yaml and create a PR with the changes (I hope).
It is difficult to test this actually works, but seems low risk even if it does not initially.

[MNT] Add workflow to update `pre-commit` hooks and make a PR

---

.github/workflows/precommit_autoupdate.yml

Updating sometimes comes with some errors, but it shouldn't stop creating a PR.
See https://github.com/aeon-toolkit/aeon/actions/runs/6607280135
Creates a new token for the PR, which should allow it to run CI as well.

[MNT] Always create a pull request on `pre-commit` update even if full run fails

---

sweep.yaml

The rules are a bit noisy currently and not creating quality PRs to make that noise worthwhile.  We can maybe revisit them at some point.

[MNT] Remove `sweep` rules and sandbox options

---

aeon/clustering/k_means.py

The default for the averaging_method was documented incorrectly. Changed default in docstring from 'mean' to 'ba'.

[DOC] Kmeans updated default for averaging method

---

.github/workflows/periodic_tests.yml
.github/workflows/pr_pytest.yml

Give codecov tests 30 minutes instead of 10 maximum runtime. Ideally it shouldnt need this much, but this gives a bit more flexibility. These can only be run manually or periodically in the night, so it should not have a massive impact to resource usage overall.

[MNT] Give more time for codecov workflow tests

---

.github/workflows/pr_opened.yml
.github/workflows/update_contributors.yml
build_tools/pr_open_commenter.py

Uses the `aeon` app access token from #881 in other GitHub workflows. This should cause the PR/Comment posted to be aeon rather than github-actions, and gives us a bit more control over permissions.

[MNT] Use app token for other GitHub workflows

---

.github/workflows/periodic_tests.yml
.github/workflows/pr_examples.yml
.github/workflows/pr_pytest.yml
.github/workflows/release.yml

Currently, the installation will occasionally fail with an SHA error when too many things are installed at once on the workflows.
I'm not quite sure what is causing this, or if there is anything on our side that can change to fix it (other than reducing the amount of dependencies).
The error is sporadic, so this PR just adds a workflow to retry the installation if it fails. Consistent failures should still be caught, as there is a limit to the amount of retries.

[MNT] Retry aeon install on failure for GitHub workflows

---

aeon/classification/shapelet_based/_rdst.py
aeon/transformations/collection/shapelet_based/_dilated_shapelet_transform.py
aeon/transformations/collection/shapelet_based/_shapelet_transform.py
aeon/transformations/collection/shapelet_based/tests/test_shapelet_transform.py

Add unequal length support for RDST transformer and classifier
Fixes #872 
For the non-numba code, use len(X) instead of shape[0] to be compatible with lists, and check for minimum length requirements in the input (i.e. all inputs must be longer than shapelets).
For the numba code, use the minimum length in fit to initialize dilations, and create a boolean mask of the size of the longer series for alpha similarity sampling. The mask is then set to false after each series length so we cannot sample points that do not exist.
No additional dependency.

[ENH] Support unequal length for rdst

---

aeon/transformations/collection/reduce.py

fixes #435 
Tabulariser converts 3D series into 2D table by concatenating attributes and returning a 2D numpy that can be used, for example, by a scikit learn estimator. Since this is impossible with unequal length series, it makes sense imo to make the internal numpy3D and just do an internal conversion rather than call the nastiness that is convert(). 
Just had a look. As far as I can see all convert() does is reshape a 3D numpy, there is currently no converters to numpyflat other than from numpy3D.

[ENH] remove nested_univ from Tabularizer

---

aeon/datasets/_data_loaders.py
pyproject.toml

Added a function ``download_dunction`` to the ``_data_loaders.py`` file.
This functions only downloads a dataset without loading it to memory.

[ENH] Add download_dataset function to _data_loaders.py

---

pyproject.toml

Removes some version upper bounds for soft dependencies.

[ENH] Remove upper bounds for `tslearn` and `pmdarima`

---

aeon/transformations/collection/tests/test_tsfresh.py
aeon/transformations/collection/tsfresh.py

Fixes #944 
switches test for tsfresh from using nested_univ and a weird conversion to numpy arrays

[ENH] remove nested_univ from TSFresh test

---

build_tools/pr_open_commenter.py
docs/installation.md

There have been multiple people on the slack unable to install `all_extras` due the the command line/shell used. This is not really a problem specific to `aeon`, but does impact us.
This PR adds a warning to the installation guide for certain shells which require a different input for dependency groups i.e. `all_extras` and `dev`.

[DOC] Add warning to installation guide for some shells

---

docs/api_reference/annotation.rst
docs/api_reference/anomaly_detection.rst
docs/api_reference/classification.rst
docs/api_reference/clustering.rst
docs/api_reference/distances.rst
docs/api_reference/regression.rst
docs/api_reference/segmentation.rst
docs/api_reference/similarity_search.rst
docs/api_reference/transformations.rst

As discussed on slack, this removes Time series from title of API modules, as its redundant and not consistent

[DOC] Remove "Time series" from API titles

---

aeon/utils/plotting.py
docs/developer_guide/deprecation.md

These were moved to the new `visualisation` package, but not deprecated from `utils`.
Clarifies a part of deprecation policy and adds new experimental modules.

[MNT] Deprecate old `plot_series` functions and policy clarification

---

aeon/classification/dictionary_based/_redcomets.py
aeon/classification/dictionary_based/tests/test_redcomets.py

Stops problem in #1052 affecting _REDCOMETS()_ but does not fix the root issue. 
RED CoMETS should z-normalise before applying both SAX and SFA but the current implementation only normalises for SAX. This PR changes how the RED CoMETS implementation does z-normalisation so that it is correctly applied for both. 
No

[BUG] Fixed missing z-normalisation for SFA in RED CoMETS

---

pyproject.toml

Somewhat of a reoccurring issue with our test suite is instability. Some of these are legitimate failures with sporadically failing tests, but a majority are just nodes crashing and causing the whole set to fail.
This would make the runs a lot more stable, but the downside of the above is it would rerun some of the legitimate failures, and they may get lost instead of being noticed and fixed. It's a bit hacky.
The main cause of these crashes from what I have gathered is `pytest-xdist` which runs the tests in parallel, and removing it would make everything a lot slower. One of the chosen plugins features is to be able to recover from hard crashed when `pytest-xdist` is installed.
One potential mitigator would be to automatically parse the output logs and create issues for re-runs which …

[MNT] Add `pytest` plugin to retry failed tests

---

pyproject.toml

CI is currently failing with `tensorflow` related errors. Sets an upper bound for the dependency.

[MNT] Set upper bound for `tensorflow`

---

aeon/classification/deep_learning/_fcn.py
aeon/regression/deep_learning/_fcn.py

The default value of '''use_mini_batch_size''' should be set to '''False''' for FCN, most of the time FCN will not be used with mini_batch.

[ENH] The Default value for use_mini_batch_size should be set to False

---

aeon/classification/deep_learning/_resnet.py
aeon/regression/deep_learning/_resnet.py

Change to `False` the default value for use_mini_batch_size in resnet for both classification and regression (the docstring already used `False` as the default value)

[REF] Fixed the default use_mini_batch_size value in resnet

---

aeon/classification/feature_based/_matrix_profile_classifier.py

Having an estimator for the matrix profile is probably not a bad idea, but it should not be this one or in the `feature_based`. Will keep if there are any objections.

[DEP] Deprecate `MatrixProfileClassifier`

---

aeon/visualisation/learning_task/tests/test_forecasting_plotting.py
aeon/visualisation/learning_task/tests/test_segmentation_plotting.py
aeon/visualisation/series/tests/test_collection_plotting.py
aeon/visualisation/series/tests/test_series_plotting.py

Some of the tests use the old imports, this did not bring up a merge conflict before being merged into main. 
Fixes the broken imports.

[BUG] Correct imports for `visualisation` testing

---

aeon/transformations/time_since.py

removes  use of is_numeric in a single location, replaced with is_any_real_numeric_dtype 
/home/runner/work/aeon/aeon/aeon/transformations/time_since.py:131: FutureWarning: PeriodIndex.is_numeric is deprecated. Use pandas.api.types.is_any_real_numeric_dtype instead
if time_index.is_numeric():

[MNT] remove is_numeric

---

aeon/clustering/__init__.py
aeon/clustering/_k_shapes.py
aeon/clustering/_kernel_k_means.py

Solves #942. See also #1091.
Adds `TimeSeriesKernelKMeans` and `TimeSeriesKShapes` to `clustering/__init__.py`.
Adds doc string example for:
- `TimeSeriesKernelKMeans` in file `_kernel_k_means`
- `TimeSeriesKShapes` in file `_k_shapes`

[DOC, REF] Add `TimeSeriesKernelKMeans` and `TimeSeriesKShapes` to `clustering/__init__.py` and also adds examples to dosctring

---

aeon/classification/deep_learning/base.py

Fixes #1109 
Corrected threshold for change of sparse argument name from sklearn version 1.1 to 1.2

[BUG] Wrong bound on sklearn for sparse argument

---

aeon/segmentation/_ggs.py
aeon/segmentation/_igts.py
pyproject.toml

Resolves #282 
Adds upper bounds for `numba` and makes the one for `scipy` more aggressive. With dependabot and our current maintenance we should be able to respond to new releases in a suitable timeframe.
Replaces `attrs` with the `dataclass` module, which while not the same is similar in functionality and is one less core dependency.

[MNT] Add upper bounds for main dependencies and replace `attrs`

---

aeon/classification/base.py

For comparison with #1104
See #1102 
Adds a `_fit_predict` and `_fit_predict_proba` method to the classifier base class. This is intended to replace the `_get_train_probs` used currently in some classifiers.

[ENH] Classification `_fit_predict` mockup

---

pyproject.toml

Updates the bound for `numba`. This version is Python 3.12 compatible, allowing progress to be made on #861.

[MNT] Update `numba` bound

---

aeon/base/estimator/hybrid/__init__.py
aeon/base/estimator/hybrid/base_rist.py
aeon/base/estimator/hybrid/tests/__init__.py
aeon/base/estimator/hybrid/tests/test_base_rist.py
aeon/classification/hybrid/__init__.py
aeon/classification/hybrid/_rist.py
aeon/regression/hybrid/__init__.py
aeon/regression/hybrid/_rist.py
docs/api_reference/base.rst
docs/api_reference/classification.rst
docs/api_reference/regression.rst

Implements `RISTClassifier` and `RISTRegressor`, inheriting from a `BaseRIST` class which holds the shared functionality. From [this publication](https://link.springer.com/chapter/10.1007/978-3-031-49896-1_8) of mine.

[ENH] RIST classifier and regressor

---

aeon/transformations/collection/convolution_based/_minirocket.py
aeon/transformations/collection/convolution_based/_minirocket_multivariate.py
aeon/transformations/collection/convolution_based/_minirocket_mv.py
aeon/transformations/collection/convolution_based/_multirocket.py
aeon/transformations/collection/convolution_based/_multirocket_multivariate.py
aeon/transformations/collection/convolution_based/_rocket.py

Typos, misspellings and sentence capitalization in the docstrings have been fixed. The docstring of the main classes in the `transformations/collection/convolution_based` module (e.g. `Rocket`, `MiniRocket`, ...) have been modified in this PR.
No

[DOC] Fix typos, misspellings & capitalizations in doctrings

---

aeon/classification/dictionary_based/_boss.py
aeon/classification/dictionary_based/_cboss.py
aeon/classification/dictionary_based/_muse.py
aeon/classification/dictionary_based/_redcomets.py
aeon/classification/dictionary_based/_tde.py
aeon/classification/dictionary_based/_weasel.py
aeon/classification/dictionary_based/_weasel_v2.py

Fixes [#1151](https://github.com/aeon-toolkit/aeon/issues/1151).  I also extended these changes to the ```_redcomets.py``` file as well , after confirming it with @baraline. 
PS : Ran the pre-commit tests as well, which passed.
**Description** : Replaced usage of  `n_instances` with `n_cases` and  `series_length`  with `n_timepoints` in dictionary classifiers' files.

[ENH] Refactored series_length and n_instances to n_timepoints and n_cases in dictionary based classifiers #1151

---

aeon/classification/shapelet_based/_rdst.py
aeon/regression/shapelet_based/__init__.py
aeon/regression/shapelet_based/_rdst.py
docs/api_reference/regression.rst

Creates a regressor version of RDST. Last of the simple pipeline classifiers to be ported for now.

[ENH] Port RDST for regression

---

aeon/transformations/collection/convolution_based/rocketGPU/__init__.py
aeon/transformations/collection/convolution_based/rocketGPU/_rocket_gpu.py
aeon/transformations/collection/convolution_based/rocketGPU/base.py
aeon/transformations/collection/convolution_based/rocketGPU/tests/__init__.py
aeon/transformations/collection/convolution_based/rocketGPU/tests/test_base_rocketGPU.py

Added a tensorflow implementation of ROCKET
Added 2 tests with the transformer

[ENH] Added rocket on gpu

---

aeon/forecasting/dynamic_factor.py
aeon/testing/expected_results/classifier_results_reproduction.py
aeon/visualisation/results/_critical_difference.py

-`type()` cant be used to check the specific type, thus we use `isinstance()` to check if an object is of a particular type. -`RandomForestCLassifier` and `SummaryTransformer` were not called but imported -Undefined name `l` was replaced by labels
from: https://github.com/aeon-toolkit/aeon/issues/1191 , See also: https://github.com/aeon-toolkit/aeon/pull/1055
closes: #1197

[REF] Refactoring some bits of code

---

aeon/testing/utils/data_gen/__init__.py
aeon/testing/utils/data_gen/_collection.py
aeon/testing/utils/data_gen/tests/test_collection.py

This PR adds a function to generate 2d unequal length time series list[np.ndarray(n_timepoints,)], which is a collection of univariate 1d time series. In addition it adds the option to choose to return_y to be consistent with other test functions in the file (such as make_example_3d_numpy and make_example_2d_numpy)

[MNT] added unequal length utils function

---

aeon/classification/convolution_based/_mr_hydra.py
aeon/classification/convolution_based/_rocket_classifier.py
aeon/regression/convolution_based/__init__.py
aeon/regression/convolution_based/_hydra.py
aeon/regression/convolution_based/_mr_hydra.py
aeon/regression/convolution_based/_rocket_regressor.py
aeon/transformations/collection/convolution_based/tests/test_multirocket_m.py
docs/api_reference/regression.rst

Implements `HydraRegressor` and `MultiRocketHydraRegressor` for regression. There is no publication for these, but the transforms for both are unsupervised. Not much change from the classification version. Tidies up the rocket classes for both classification and regression.

[ENH] Hydra and MultiRocketHydra for regression

---

aeon/transformations/collection/shapelet_based/_shapelet_transform.py

Fixes an issue in `RandomShapeletTransform` where a check of std against 0 is used, elsewhere we compare against `AEON_NUMBA_STD_THRESHOLD`. Checked after seeing https://github.com/sktime/sktime/pull/6141, credit to them.

[BUG] RandomShapeletTransform stdev fix

---

aeon/datasets/_data_writers.py

* Parameter now passed correctly.
Saving a collection of time series in np.ndarrays or list format with the write_to_tsfile method did not create the header correctly. A parameter was missing and is now passed.
No.
My first ever PR, let me know if there is anything to improve!
Unsure if this is a BUG or MNT.

[BUG] write_to_tsfile not writing header

---

aeon/transformations/collection/channel_selection.py
aeon/transformations/collection/tests/test_channel_selection.py

Part of developing a wider selection of channel selection transformers, see #1270

[DEP] deprecate ElbowClass prior to move to dedicated package

---

aeon/classification/distance_based/_shape_dtw.py

Referring to issue #788 
The implementation supposes that shapeDTW with knn is simply knn-dtw on transformed series, this is false.
As shapeDTW distance does 2 steps:
- step 1: find dtw path on transformed series
- step 2: transfer the path on the pairwise distance between the two raw series and calculate a dtw value based on this new path

[DEP] Deprecating ShapeDTW classifier, to be replaced with a newer correct version

---

aeon/base/_base_series.py
aeon/base/tests/test_base_series.py
aeon/testing/mock_estimators/__init__.py
aeon/testing/mock_estimators/_mock_series_transformers.py
aeon/transformations/series/base.py
aeon/transformations/series/tests/test_base.py
docs/developer_guide/deprecation.md

This introduces a new function in BaseSeriesEstimator called _postprocess_series that checks the axis  passed and is different to self.axis, then the series is transposed back to the axis passed.
It also squeezes the output for univariate only transformers back to being univariate. See #1375 for how this may change subsequently.
this function is called in  BaseSeriesTransformer in transform, fit_transform and inverse_transform  as follows
```python
if axis is None:
axis = self.axis
X = self._preprocess_series(X, axis=axis)
Xt = self._transform(X)
return self._postprocess_series(Xt, axis=axis)
```

[ENH] BaseSeriesTransformer maintains axis for user determined output with BaseSeriesEstimator function

---

docs/api_reference/classification.rst
docs/api_reference/regression.rst

Assuming the updates to docs/api_reference were done in error, these changes add entries for classifiers implemented in the following PRs:
- https://github.com/aeon-toolkit/aeon/pull/1221
- https://github.com/aeon-toolkit/aeon/pull/1173
I didn't do an exhaustive search for implemented classifiers that aren't in the API reference, so there may be some greatness that's still (relatively) hard to discover.
 

[DOC] Adds previously implemented classifiers to docs/api_references

---

aeon/classification/compose/_ensemble.py

The current docstring for the `classifiers` parameter of `WeightedEnsembleClassifier` is not correct.
This change updates the docstring to match what other ensemble docstrings look like (see [forecasing.compose._ensemble.py](https://github.com/aeon-toolkit/aeon/blob/5f8974f3fca240f66cb52a626658931489871962/aeon/forecasting/compose/_ensemble.py#L46-L47))
No

[DOC] Correct `WeightedEnsembleClassifier` parameter docstring

---

aeon/utils/conversion/_convert_series.py

subsequent to https://github.com/aeon-toolkit/aeon/pull/1338, test test_wrapper_series_mtype failing an overnight test. This function passes an (n,1) np.ndarray to a forecaster and tries to convert it to a pd.Series. Now the conversion squeezes before testing ndim > 1.

[ENH] allow np.ndarray with ndim>1 to convert to pd.series when squeezable to 1D

---

aeon/clustering/tests/test_k_means.py

This PR splits up and makes the kmeans-ba tests run faster and are easier to read.
The updated test was timing out in the nightly CI runs. While I don't think it was directly the cause (think the runner was dodgy) this test should be split up and simplified anyway so this PR fixes that.

[MNT] split up and simplified ba test

---

aeon/forecasting/tests/test_interval_wrappers.py

replaces convert_to with convert_series function in use elsewhere see https://github.com/aeon-toolkit/aeon/issues/1142

[ENH] remove datatypes call from test_interval_wrappers

---

aeon/transformations/tests/test_base.py
aeon/utils/validation/_input.py

replaces mtype_from_scitype with abstract type function in use elsewhere see #1142

[ENH] remove datatypes call from transformations test function

---

aeon/clustering/_k_means.py
aeon/clustering/tests/test_k_means.py

This PR adds a strategy to kmeans to handle/allow empty clusters. If a empty cluster occurs then the time series that contributes the most to sum of squared error (the time series furthest distance from its assigned cluster centre) is set to be a cluster centre.
This follows the same logic sklearn does to handle empty clusters.

[ENH] Kmeans allow empty clusters

---

aeon/classification/shapelet_based/_rdst.py
aeon/transformations/collection/shapelet_based/_dilated_shapelet_transform.py
aeon/transformations/collection/shapelet_based/tests/test_dilated_shapelet_transform.py

Fixes #1444 
Fix sporadic doctest failure. At the end of shapelet extraction, a check is performed to remove shapelets which values were full of 0. This should happen if a shapelet is pruned during the extraction process, the value of 0 is due to the initialization of the array of shapelet values as full of 0 (`np.zeros`). But as the covid dataset has long successive 0 values, it was possible that they were all pruned with bad luck, causing the failure.
The test is now based on `np.inf` value, and the array initialized as full of `np.inf` to avoid any problem related to input values.

[BUG] Fix RDST doctest failure & numba deprecration warning

---

aeon/forecasting/compose/tests/test_multiplex.py
aeon/forecasting/model_evaluation/_functions.py
aeon/forecasting/model_selection/_tune.py
aeon/transformations/tests/test_multiplexer.py
aeon/utils/validation/forecasting.py

deprecates the function check_scorer. This function is used in some places to set a scoring function through a call to check_scorer(None). This is confusing, and it is much clearer imo to set the scorer explicitly. This PR does that and tags the function for deprecation.

[DEP] deprecate check_scorer

---

aeon/transformations/collection/convolution_based/_multirocket_multivariate.py

Fixes #1278
Random state was not set in outside of numba function, which, as both need to be set (see [docs](https://numba.readthedocs.io/en/stable/reference/numpysupported.html#initialization)). This caused difference in accuracy during some tests.
Using the new numpy random generator would bump numba version to `0.56` from `0.55`, so I stick with the old numpy random seed.

[BUG] Fix MultiRocketMultivariate failures

---

.all-contributorsrc
aeon/datasets/tests/test_load_forecasting.py
aeon/transformations/outlier_detection.py

Fixes #1452 
Corrects spelling of  'lenght' to 'length'.
No.
No.
- [ x] I've added myself to the [list of contributors](https://github.com/aeon-toolkit/aeon/blob/main/.all-contributorsrc). Alternatively, you can use the [@all-contributors](https://allcontributors.org/docs/en/bot/usage) bot to do this for you.
- [ x] The PR title starts with either [ENH], [MNT], [DOC], [BUG], [REF], [DEP] or [GOV] indicating whether the PR topic is related to enhancement, maintenance, documentation, bugs, refactoring, deprecation or governance.

[DOC] PR #1452

---

aeon/utils/validation/_dependencies.py

Fixes #1395
Allow release candidate version in python version checking.

[BUG] Dependencies version checking not handling python release candidate correctly

---

aeon/classification/hybrid/_rist.py
aeon/classification/interval_based/_cif.py
aeon/classification/interval_based/_drcif.py
aeon/classification/interval_based/_rise.py
aeon/classification/interval_based/_rstsf.py
aeon/classification/interval_based/_stsf.py
aeon/regression/hybrid/_rist.py
aeon/regression/interval_based/_cif.py
aeon/regression/interval_based/_drcif.py
aeon/regression/interval_based/_rise.py

Bug fix for certain estimators based on the current failing coverage tests. Didn't look into why for now, but setting tags dynamically prior to `__init__` will reset them.

[BUG] Set dynamic tag after `__init__` for classifiers and regressors.

---

aeon/datatypes/_adapter/gluonts_to_pd_multiindex.py
aeon/datatypes/_adapter/pd_multiindex_to_list_dataset.py

I marked two gluonts related functions for moving to utils, but actually moving them is problematic, see slack discussion. They can stay in datatypes until that is removed

[DEP] remove deprecation for datatypes adapter functions

---

docs/index.md
pyproject.toml

1. Changes about text from  "A toolkit for conducting machine learning tasks with time series data" to "A toolkit for machine learning from time series". The current text does not scan, "conducting machine learning tasks" doesnt seem to make sense to me
2. Added an explicit link to github from the top of aeon-toolkit.com.

[DOC] Change about text, add a link from docs to repo

---

aeon/classification/distance_based/_elastic_ensemble.py
aeon/classification/distance_based/_time_series_neighbors.py
aeon/classification/sklearn/_rotation_forest_classifier.py

Reference Issues/PRs
Part of https://github.com/aeon-toolkit/aeon/issues/1454
What does this implement/fix? Explain your changes.
Adding type hints to remaining scripts in :  aeon.classification.distance_based module, and improvements based on earlier feedback. 
Added type hints to "aeon/classification/sklearn/_rotation_forest_classifier.py"
Does your contribution introduce a new dependency? If yes, which one?
None
Any other comments?
Type hints are NOT added in other methods since they were not primitive types.

[ENH] Type hints for primitives and string arguments:Part2

---

.all-contributorsrc
aeon/classification/feature_based/_fresh_prince.py

Closes: #1511 
This PR adds a reference to the following paper: 
https://link.springer.com/chapter/10.1007/978-3-031-09282-4_13
in the FreshPRINCEClassifier docstring.

[DOC] Add reference to paper in FreshPRINCEClassifier

---

aeon/base/_base.py
aeon/classification/sklearn/_continuous_interval_tree.py
aeon/classification/sklearn/_rotation_forest_classifier.py
aeon/classification/sklearn/tests/test_continuous_interval_tree.py
aeon/exceptions.py
aeon/forecasting/model_evaluation/_functions.py
aeon/forecasting/model_evaluation/tests/test_evaluate.py
aeon/forecasting/model_selection/_tune.py
aeon/forecasting/tests/test_all_forecasters.py
aeon/regression/sklearn/_rotation_forest_regressor.py
aeon/testing/test_all_estimators.py

This file contains unused or duplicate functions from `scikit-learn`. I don't really see the need in keeping it, and if we need exceptions in the future it should not be in the top level of the package.

[DEP] Deprecate `exceptions.py`

---

aeon/classification/distance_based/_elastic_ensemble.py

Closes: #1496 
-  Changes `dwdtw` to `wddtw` in the Parameters section of distance_measures 
-  Header changed from Notes to References
-  Modifies docstring for `get_metric_params()`
-  Adds docstring for `_get_100_param_options()`

[DOC] Update the `ElasticEnsemble` documentation

---

aeon/benchmarking/results_loaders.py
aeon/datasets/tsc_datasets.py

this changes the results loaders to use http://timeseriesclassification.com because there is a current issue with the security certificate after website transfer. Also corrects a typo in the univariate2015 list.

[ENH] Results lists and loading

---

CODEOWNERS

None, maybe #1095
- removes @ermshaua, not a core dev
- fixes name of _code of conduct_ team
Nope

[BUG]: Fix CODEOWNERS file

---

aeon/transformations/series/__init__.py
aeon/transformations/series/_theta.py
aeon/transformations/series/tests/test_theta.py
aeon/transformations/theta.py

[ENH] Convert Theta transform to series transformer

---

aeon/clustering/averaging/_ba_petitjean.py
aeon/clustering/averaging/_ba_subgradient.py
aeon/clustering/averaging/_barycenter_averaging.py

Solve #1251 
- Added weighted version of elastic barycenter by adding an optional parameter (weights, by default equals to ones)
- Fixed the cache issue in sub gradient method by making a copy of barycenter 
No
No

[ENH,BUG] added weighted elastic barycenter and fix cache issue in subgradient method

---

aeon/classification/shapelet_based/_ls.py
aeon/classification/shapelet_based/_mrsqm.py
aeon/classification/shapelet_based/_rdst.py
aeon/classification/shapelet_based/_sast_classifier.py
aeon/classification/shapelet_based/_stc.py
aeon/classification/sklearn/_continuous_interval_tree.py

Reference Issues/PRs
Part of https://github.com/aeon-toolkit/aeon/issues/1454
What does this implement/fix? Explain your changes.
Adding type hints to remaining scripts in : aeon/classification/sklearn/_continuous_interval_tree.py ( Existing class _TreeNode, has been moved above ContinuousIntervalTree, in order to include the type[_TreeNode] in the type hints)  
aeon/classification/shapelet_based scripts. 
Does your contribution introduce a new dependency? If yes, which one?
None
Any other comments?
Type hints are NOT added in other methods since they were not primitive types.

[ENH] Type hints for primitives and string arguments:Part3

---

aeon/transformations/collection/dwt.py
aeon/utils/numba/tests/test_wavelets.py
aeon/utils/numba/wavelets.py

None
In preparation of adding the DWT-MLEAD anomaly detection method, I moved the DFT implementation for `aeon.transformations.collections.DWTTransformer` to a common place in `aeon.utils`.
- Moves the implementation of the Haar wavelet to a separate module `aeon.utils.numba.wavelets`
- Applies `@njit` to the implementation
- Replaces `DWTTransformer`-code with a call to the util-method.
Nope
⬆️  **should I do this?**

[MNT] Move haar wavelet transform to aeon.utils.numba package

---

aeon/clustering/__init__.py
aeon/clustering/dummy.py
aeon/clustering/tests/test_dummy.py

[ENH] Add DummyClusterer

---

aeon/base/_base.py
docs/api_reference/transformations.rst

none
`SlidingWindowSegmenter` was missing in the API reference, added now.

[DOC] Add SlidingWindowSegmenter to API reference

---

aeon/distances/_lcss.py
aeon/distances/tests/test_pairwise.py

fixes #761 by just lower bounding LCSS to zero to avoid numba numerics, adds a test for all distances >=0

[BUG] lcss bounded below to 0

---

aeon/transformations/collection/convolution_based/_minirocket.py
aeon/transformations/collection/convolution_based/_multirocket.py
aeon/transformations/collection/convolution_based/_multirocket_multivariate.py
aeon/transformations/collection/convolution_based/tests/test_all_rockets.py

See #1606 
Currently some rocket transforms convert to 32 bit, some convert to 64 bit, some do not conversion at all. This PR makes them all 32 bit
1. MultiRocket
currently converts 64 bit in fit, does nothing in transform but expects 64 bit
fit:        X = X.astype(np.float64)
transform: nothing
**now**
fit and transform to 32, number decorator in _transform now
@njit(
"float32[:,:](float32[:,:],float32[:,:],Tuple((int32[:],int32[:],float32[:])),"
2.  MultiRocketMultivariate
fit:   X = X.astype(np.float64)
transform: nothing
**now**
fit and transform to 32, number decorator in _transform now
@njit(
"float32[:,:](float32[:,:],float32[:,:],Tuple((int32[:],int32[:],float32[:])),"
3. MiniRocket
fit and transform:         X = X[:, 0, :].astype(np.float32)
now squeeze for same as others
4. …

[BUG] Convert rockets to only use 32 bit floats internally

---

aeon/testing/test_config.py

Fixes #1067 which no longer seems an issue

[BUG] unexclude mock forecaster

---

aeon/utils/sampling.py
aeon/utils/tests/test_windowing.py
aeon/utils/windowing.py
pyproject.toml

none
Adds two functions to a new utility module `aeon.utils.windowing`:
- `sliding_windows(X, window_size, stride, axis=1)` to create a sliding window view on a time series
- `reverse_windowing(y, window_size, reduction, stride, padding_length)` to reverse window anomaly scores to point anomaly scores
The windowing functions will be used in the implementation of `KMeansAnomalyDetector` and the `PyODAdapter` (#1586).
The new util functions are not added to the API reference.
no

[ENH] Add sliding window utils for anomaly detection module

---

.github/workflows/pr_precommit.yml

The current trigger for PRs in the pre-commit workflow does not give sufficient permissions to use repository secrets in forks. We don't actually install or execute any user code in this workflow, so I don't see the issue with giving it said permissions.

[MNT] Change pre-commit trigger type

---

aeon/distances/_dft_sfa_mindist.py
aeon/distances/_paa_sax_mindist.py
aeon/distances/_sax_mindist.py
aeon/distances/_sfa_mindist.py
aeon/transformations/collection/dictionary_based/_sfa.py
aeon/transformations/collection/dictionary_based/_sfa_fast.py

- This potentially fixes the following bug in doctests by setting the word length from 16 to 8.
- Adds a check for the word-length not to be larger than the TS length in SFA and SFA_FAST to avoid this error.
> [gw2] linux -- Python 3.10.14 /opt/hostedtoolcache/Python/3.10.14/x64/bin/python
> 045     >>> transform = SFAFast(
> 046     ...    word_length=16,
> 047     ...    alphabet_size=8,
> 048     ...    window_size=x.shape[-1],
> 049     ...    norm=True,
> 050     ...    lower_bounding_distances=True   # This must be set!
> 051     ... )
> 052     >>> transform.fit(x)
> 053     SFAFast(...)
> 054     >>> x_sfa = transform.transform_words(x).squeeze()
> UNEXPECTED EXCEPTION: IndexError('index 8 is out of bounds for axis 2 with size 8')

[BUG] Bugfix MinDist doctests by setting word_length to 8

---

aeon/datasets/tests/test_tsad_data_loader.py
examples/datasets/load_data_from_web.ipynb
pyproject.toml

Fixes #1677
- uses `pytest-mock` to save local data to temporary directory in tests
- fix dataset example notebooks
- `pytest-mock` in `[dev]`

[BUG] Fix TSAD data loading tests and example notebooks

---

.github/workflows/periodic_tests.yml
.github/workflows/pr_pytest.yml
.github/workflows/release.yml
pyproject.toml

From discussion in Slack. Threading removes defaults and does other things which can make debugging more complicated, which is usually the purpose of local `pytest` runs.
Removes the default configuration for threading and adds it manually to `pytest` calls in the CI.
The CI can still be threaded locally but now need an argument to do so.

[MNT] Disable `pytest` threading by default for local runs

---

.github/workflows/periodic_tests.yml
.github/workflows/pr_pytest.yml
.github/workflows/release.yml
README.md
aeon/testing/test_all_estimators.py
pyproject.toml

Drops support for Python 3.8. This is near its end of life soon, and is causing some issues with `tensorflow`.
I would give this a bit of time for discussion before merging.

[MNT] Drop Python 3.8

---

aeon/classification/feature_based/_fresh_prince.py
aeon/classification/sklearn/_continuous_interval_tree.py
aeon/classification/sklearn/_rotation_forest_classifier.py
aeon/regression/feature_based/_fresh_prince.py
aeon/regression/sklearn/_rotation_forest_regressor.py
aeon/regression/sklearn/tests/test_all_regressors.py
aeon/regression/sklearn/tests/test_rotation_forest_regressor.py

- Adds `ClassifierMixin` and `RegressorMixin` to sklearn estimators
- Carries out some deprecation actions for the classifier
- Adds `sklearn` testing for regressor rotf
- Makes some changes to data processing to accommodate for the above

[ENH] Tidy, deprecation actions and testing for sklearn estimators

---

aeon/transformations/date.py
aeon/transformations/exponent.py
aeon/transformations/feature_selection.py
aeon/transformations/fourier.py
aeon/transformations/func_transform.py

Deprecate
1. DateTimeFeatures
2. FunctionTransformer
3. FourierFeatures
4. FeatureSelection
5. ExponentTransformer
unless someone wants to convert them to SeriesTransformers, all will be either removed or parked in _legacy until the big bang

[DEP] Dep fest

---

aeon/clustering/base.py
aeon/clustering/feature_based/_catch22.py
aeon/clustering/feature_based/_summary.py
aeon/clustering/feature_based/_tsfresh.py

There were two edge cases with the clustering predict_proba function that would cause crashes.
1) If there wasn't at least 1 prediction in every cluster
2) If the prediction didn't use cluster values of 0-n_clusters. For example I used a k-medoids package that when predict was called returned [22, 22, 32, 3, 32, 22] where instead of the cluster values being a value from 0-n_clusters it was referring to the index of the cluster centre that each value was assigned to. 
This PR makes two main changes to address the above.
1) Instead of using .shape[0] to create the dist array n_clusters is used (when available isn't required):
```
n_clusters = self.n_clusters
if n_clusters is None:
n_clusters = int(max(preds)) + 1
dists = np.zeros((X.shape[0], n_clusters))
```
2) A additional sanitisation of …

[BUG] Cluster predict proba edge cases

---

aeon/classification/deep_learning/_cnn.py
aeon/classification/deep_learning/_encoder.py
aeon/classification/deep_learning/_fcn.py
aeon/classification/deep_learning/_inception_time.py
aeon/classification/deep_learning/_lite_time.py
aeon/classification/deep_learning/_mlp.py
aeon/classification/deep_learning/_resnet.py
aeon/classification/deep_learning/base.py
aeon/clustering/deep_learning/_ae_fcn.py
aeon/clustering/deep_learning/_ae_resnet.py
aeon/clustering/deep_learning/base.py
aeon/regression/deep_learning/_cnn.py
aeon/regression/deep_learning/_encoder.py
aeon/regression/deep_learning/_fcn.py
aeon/regression/deep_learning/_inception_time.py
aeon/regression/deep_learning/_lite_time.py
aeon/regression/deep_learning/_mlp.py
aeon/regression/deep_learning/_resnet.py
aeon/regression/deep_learning/base.py

Fix #1098 
Adds a function to base to append a modelcheckpoint whenever the user does not use the default callbacks
the reason to insist on using modelcheckpoint is because not using the best model for predict simply doesnt make sense :)
Tried the code of the above issue, its working now

[BUG] Adding modelcheckpoint callback by default to deep learners when user chooses their own callbacks list

---

pyproject.toml

aeon does not work properly with tensorflow 2.13, see https://github.com/aeon-toolkit/aeon/issues/1477. The current version is 2.16. Conversations with @hadifawaz1999 suggest it is not worth the effort to make things work as the signatures keeps changing. In my experience tensorflow is notoriously bad at backward compatibility, so it makes sense just to enforce a bound I think. Interaction with python 3.12 is still an issue!
Closes https://github.com/aeon-toolkit/aeon/issues/1477

[MNT] Raise tensorflow bound to >2.13

---

aeon/classification/deep_learning/tests/test_random_state_deep_learning.py
aeon/clustering/deep_learning/tests/test_random_state_deep_learning_cluster.py
aeon/regression/deep_learning/tests/test_random_state_deep_regressor.py

same issue we had with LCSS failing, should use almost equal and not equal, random fails on CI even when arrays are equal (floating point issues)

[BUG] Use almost equal in random state testing of deep learning

---

aeon/base/_base_collection.py
aeon/base/tests/test_base_collection.py
aeon/classification/base.py
aeon/classification/tests/test_base.py
aeon/utils/validation/collection.py

fixes #1712 
Stores the length of the first series and number of channe;ls in the metadata in fit, which is then checked against the series length/number of channels  in predict and predict proba. Note
1. Because of the number of supported data types, best way is to call a method get_n_timepoints/n_timepoints in validation
2. For variable length data structures it just looks at the length of the first element, and does not do the test if the classifier has unequal_length capability. If the collection is in fact unequal length, then it fails before here. Only case is where it is in an np-list but they are all in fact equal length. This tests if that common length is different to that seen in train 
3. n_channels only checked for multivariate capable classifiers
4. will move the checking …

[BUG] Store n_timepoints and n_channels in fit to check in transform

---

aeon/transformations/collection/convolution_based/_hydra.py

Hydra does not have a `_fit` currently unlike other convolution transforms. It should have, as it does not really make sense to generate new kernels each transform.
Found by @angus924

[BUG] Hydra bugfix

---

aeon/transformations/collection/channel_selection/tests/test_channel_scorer.py

changes the channel selector test to make the issue of a single class value on CV very unlikely

[ENH] channel selector test

---

aeon/base/estimator/compose/collection_pipeline.py

Fixes #1748 
adds this to fit_transform to make sure the attribute in self._steps is stored in self.steps_ in (name,estimator) pairs, as is the convention it seems
```python
def _fit_transform(self, X, y=None) -> np.ndarray:
self.steps_ = self._check_estimators(
self._steps, attr_name="steps_", cls_type=SklearnBaseEstimator
)
Xt = X
for i in range(len(self.steps_)):
Xt = self.steps_[i][1].fit_transform(X=Xt)
return Xt
```

[BUG] Add names to create steps_ in CollectionPipeline

---

aeon/classification/dictionary_based/__init__.py
aeon/classification/dictionary_based/_mrsqm.py
aeon/classification/shapelet_based/__init__.py
aeon/testing/expected_results/classifier_results_reproduction.py
docs/api_reference/classification.rst

move requested by the algorithm authors

[DEP] Move MRSQM to dictionary based

---

docs/getting_started.md

Fixes #11841.
No additional dependencies.
The decision for removing the redundant 'n_timepoints'  was supported by Antoine.

[DOC] Typo correction in getting started guide

---

aeon/networks/tests/test_all_networks.py
aeon/networks/tests/test_cnn.py
aeon/networks/tests/test_inception.py

Improves #1233
Add network specific tests to improve coverage of DL networks :
* inception network coverage 67% -> 100%
* encoder network coverage 13% -> 100%
* cnn network coverage 98% -> 99% (last percent is from a deprecated class)
No
AE networks have been ignored as they already have someone working on it with specific tests [ref](https://github.com/aeon-toolkit/aeon/pull/1851#discussion_r1694029339).
There are also 2 networks that can have a better coverage (lite and tapnet) but that have been ignored as they are already skipped in test_all_networks, see #1867.

[ENH] Improve deep learning networks test coverage

---

examples/distances/distances.ipynb

1) Sum of squares equation is missing square -> added ^2
2) Sentence grammar error, missing "as" ->added "as"
- No

[DOC] Fix 2 typos in distances notebook

---

aeon/forecasting/tests/test_all_forecasters.py
aeon/networks/_ae_fcn.py

Fixes #1540 
Docstrings weren't following numpy style guide. Corrected the sections titled Arguments to be Parameters. In the base.y there is a use of Arguments however this is correct, [classes can use a section with this title](https://numpydoc.readthedocs.io/en/latest/format.html#class-docstring).
No.
I found the first instance as described by @aadya940 then used the case-sensitive search in vscode for the remaining inconsistencies.
This is a continuation of an earlier PR for which not all changes were accepted.

[DOC] Converging towards numpy doc standards V2 - issue #1540 

---

aeon/base/_base_collection.py
aeon/utils/validation/collection.py

Related to #1888
1. Add exceptions in `get_n_channels` to be raised if list of 2D numpy/pandas don't have consistent channels.
2. Replace some `aeon.registry.COLLECTIONS_DATA_TYPES` in doc with `aeon.utils.registry.COLLECTIONS_DATA_TYPES` to have correct path.
3. Fix `get_n_channels` doc (was copied and pasted from `get_n_timepoints`)
No.
In `get_n_timepoints` doc : 
```
Handles the single exception of multi index DataFrames. If unequal length series,
returns the length of the first series.
```
`get_n_cases` and `get_n_channels` have the doc : 
```
Handle the single exception of multi index DataFrame.
```
I don't get the doc, so I would like another opinion for what it means in `get_n_cases` and `get_n_channels`.

[BUG] get_n_channels check channels consistent

---

CONTRIBUTORS.md
docs/developer_guide/dev_installation.md

Issue #1914
There is a problem where `pip install --editable .[dev]` needs to have quotation marks `pip install --editable ."[dev]"` because of how your shell handles special characters.
It was explained in the documentation, but the solution was at the bottom of the section not so close to the issue that it was explaining, so the solution was moved in order to be immediately after the issue.

[DOC] Change order of build and install instructions for clarity

---

docs/developer_guide/dev_installation.md
docs/installation.md

Issue #1914
The second pull request for the issue above as more improvements were found during the discussion.
dev-installation.md got an error solution turned into a note
installation.md got grammar and spelling corrected

[DOC] Grammar corrections to developer installation and installation

---

aeon/clustering/_clara.py
aeon/clustering/tests/test_clara.py

This PR fixes a bug with the CLARA clusterer where it was using the inertia of the subset of time series rather than across the whole dataset to determine the best version.

[BUG] Fixed CLARA issue

---

aeon/similarity_search/base.py
aeon/similarity_search/query_search.py

Issue: #1901 
Updated type hints for `base.py` and `query_search.py` in the `similarity search` module.
Updated documentation in many places to say `X : np.ndarray, 2D array of shape (x, y)` or `X : np.ndarray, 3D array of shape (x, y, z)` as suggested in Slack discussion.

[DOC] Update type hints for similarity search

---

aeon/classification/compose/tests/test_ensemble.py
aeon/testing/data_generation/_collection.py

Fixes #1973
Adds a parameter to raise the minimum number of class labels in a generated dataset. Sets this to 2 for a currently breaking test which uses CV.

[ENH] Add minimum number of class labels for numpy data generators

---

aeon/transformations/series/__init__.py
aeon/transformations/series/_dft.py
aeon/transformations/series/tests/test_dft.py
docs/api_reference/transformations.rst

Implement DFT asked in #1920.
Add a new transformation, named `DFTSeriesTransformer`.
The simplified algorithm is the following : 
1. Compute FFT
2. Remove a proportion of terms (r paramter)
3. Compute invert FFT
No.
Removed terms can be sorted by amplitude before removal to keep most important terms instead of first ones.
I based my code using `BKFilter` class as a template.
-> I will use the bot when the PR is considered as ok.

[ENH] Discrete Fourier Approximation Transformer

---

aeon/transformations/collection/shapelet_based/_shapelet_transform.py

- Part of #1910
- References #1454
- Add type hints to `__init__` method in _shapelet_transform.py
- New dependency added: "typing" library
1) Did not type parallel_backend because one types is "ParallelBackendBase", and did not know how to add that
2) "contract_max_n_shapelet_samples" type -> Union[int, float] because np.inf (float type) is a default
3) "time_limit_in_minutes" type -> Union[int, float] for flexibility. Documentation had int, but default value was 0.0 originally.

[ENH] add type hints to _shapelet_transform.py __init__ method

---

aeon/transformations/collection/shapelet_based/_rsast.py
aeon/transformations/collection/shapelet_based/_sast.py

What does this implement/fix? Explain your changes.
Added type hints for rsast and sast files under shapelet based collection transformation.
#1910

Added type hints for rsast and sast files

---

.github/workflows/fast_release.yml

A workflow to make releases without running tests. Should not be used in regular circumstances. Adding now because we need a release for ECML and the old Ubuntu runner bug for extended testing has reappeared.

[MNT] Fast release workflow

---

aeon/datasets/tsc_datasets.py

See also #1828
Add  `univariate_bake_off_2024` to tsc_datasets with the 30 new univariate classification problems used in the bake off.
Also add the missing reference the the bake off paper.
No.
Choice was to create a "new 30 problem" collection, but we may want to add the new (not all the 30) problems to the 128 UCR univariate collection.
-> I will use the bot when the PR is considered as ok.

[MNT] Update TSC Datasets

---

examples/classification/shapelet_based.ipynb

Fixes #2007 
Added an explanation as to why the shapeletclassifiervizualiser doesn't support certain classifiers, specifically the rotational forest.
added the following md section to the shapelet_based notebook: 
Similarly to visualizing transformers, we can also visualize individual shapelets of a shapelet-based classifier, and, when possible, plot the best shapelets based on feature importance criterions of some estimators. The scope of these estimators is generally limited to those inheriting from scikit-learn’s BaseDecisionTree, BaseForest, or LinearClassifierMixin classes, as these are known to be among the most interpretable models where feature weights directly relate to the input features.
For instance, in aeon's Rotational Forest, the application of Principal Component Analysis …

[ENH] Documented why rotational forest isn't visualisable in the shapelet viz module

---

aeon/transformations/series/_exp_smoothing.py
aeon/transformations/series/tests/test_exp_smoothing.py

- Part of #1920
- Add smoothing filter ExpSmoothingSeriesTransformer (note abbreviated Exp)
- Tests check for different alpha, and window_size values
- No new dependencies. Imports libraries: numpy, typing
- [Arxiv paper reference](https://arxiv.org/abs/1811.00894) has an error in the exponential smoothing equation. The decaying term should be based on s_j-1, and not t_j-1 . I'm not sure what the [Springer reference](https://doi.org/10.1007/978-3-030-29859-3_5) has. I do not have access
Paper:  s_0 = t_0 and s_j = alpha * t_j + (1 - alpha) * t_j-1
Corrected: s_0 = t_0 and s_j = alpha * t_j + (1 - alpha) * s_j-1
- Allows user to use "alpha" or "window_size". If "window_size" is specified, alpha is overwritten with 2. / (window_size + 1)
- For the reference paper link, I added an arxiv link …

[ENH] add BaseSeriesTransformer - ExpSmoothingSeriesTransformer

---

aeon/anomaly_detection/_pyodadapter.py
aeon/anomaly_detection/_stomp.py
aeon/clustering/_k_shape.py
aeon/clustering/_k_shapes.py
aeon/clustering/_kernel_k_means.py
aeon/segmentation/_binseg.py
aeon/segmentation/_fluss.py
aeon/transformations/series/_acf.py
aeon/transformations/series/_matrix_profile.py

none, but inspired by [this PR comment](https://github.com/aeon-toolkit/aeon/pull/2091#discussion_r1775678022)
- removes redundant calls to `_check_soft_dependencies` in estimators (this is already done by the `__init__`-function of the base classes
- adds the correct version bound for `pyod` in `PyODAdapter` since a new version with the `pyod.__version__`-attribute was published
no

[MNT] remove redundant soft dependency checks

---

aeon/transformations/base.py

Only other base classes extend from `BaseTransformer` currently, and the goal is to have it remain this way in lieu of specific series and collection transformers. There is no need for it to have its own functionality, so this PR converts it into a simple abstract class for other base transformers for now.

[ENH] Convert `BaseTransformer` into an abstract class

---

aeon/classification/sklearn/_continuous_interval_tree.py

#1345 
Using numpy.unique to replace the original code as suggested in  #1345 
No
Thing goes well, and thank aeon to let me know the pipeline about a repo

[MNT]Use Numpy Vectorization in ContinuosIntervalTree fit method #1345

---

aeon/anomaly_detection/_left_stampi.py
aeon/base/_base.py
aeon/base/estimator/compose/collection_pipeline.py
aeon/base/tests/test_base.py
aeon/classification/compose/tests/test_pipeline.py
aeon/classification/deep_learning/_inception_time.py
aeon/classification/deep_learning/_lite_time.py
aeon/classification/deep_learning/base.py
aeon/classification/dictionary_based/_mrsqm.py
aeon/classification/shapelet_based/_ls.py
aeon/classification/shapelet_based/_rdst.py
aeon/clustering/compose/tests/test_pipeline.py
aeon/clustering/deep_learning/base.py
aeon/regression/compose/tests/test_pipeline.py
aeon/regression/convolution_based/_mr_hydra.py
aeon/regression/deep_learning/_inception_time.py
aeon/regression/deep_learning/_lite_time.py
aeon/regression/deep_learning/base.py
aeon/regression/shapelet_based/_rdst.py
aeon/testing/estimator_checking/_estimator_checking.py
aeon/testing/estimator_checking/_yield_estimator_checks.py
aeon/transformations/base.py
aeon/transformations/collection/_pad.py
aeon/transformations/collection/_truncate.py
aeon/transformations/collection/base.py
aeon/transformations/collection/compose/tests/test_pipeline.py
aeon/transformations/collection/convolution_based/rocketGPU/base.py
aeon/utils/tags/_tags.py
aeon/utils/tags/tests/test_lookup.py
aeon/utils/tags/tests/test_validate.py

Renames tags to replace `-` with `_` and replaces the odd `:removes` capability tag names.

[REF] Rename tags

---

aeon/anomaly_detection/base.py
aeon/anomaly_detection/tests/test_base.py
aeon/base/_base.py
aeon/base/tests/test_base.py
aeon/classification/base.py
aeon/classification/deep_learning/base.py
aeon/classification/dictionary_based/_boss.py
aeon/classification/early_classification/base.py
aeon/classification/hybrid/_rist.py
aeon/classification/shapelet_based/_ls.py
aeon/clustering/_k_means.py
aeon/clustering/base.py
aeon/regression/base.py
aeon/regression/deep_learning/base.py
aeon/regression/hybrid/_rist.py
aeon/segmentation/_eagglo.py
aeon/segmentation/base.py
aeon/testing/estimator_checking/_yield_estimator_checks.py
aeon/transformations/collection/_resize.py
aeon/transformations/collection/base.py
aeon/transformations/collection/channel_selection/_elbow_class.py
aeon/transformations/collection/dictionary_based/_sfa.py
aeon/transformations/collection/dictionary_based/_sfa_fast.py
aeon/transformations/collection/feature_based/_catch22.py
aeon/transformations/series/base.py

- replaces `_is_fitted` and the `is_fitted` property with just an `is_fitted` attribute
- requires `_tags_dynamic` be present (I do not know why it would be gone, but there are checks for some reason)
- requires a `parameter_set` argument for `get_test_params` method
- removes `create_test_instances_and_names` method (no usages, cant see why it would be useful for users)
- removes `is_composite` method. I don't know why you would want this, but it should be a tag if it stays
- adds some overloads for `sklearn` private methods to make them more compatible with our framework (or raise a better error where there is no compatibility)

[ENH] More `BaseEstimator` method and attribute changes

---

aeon/transformations/collection/_periodogram.py

fixes #2168 
Sets the dynamic tag "python_dependencies": "pyfftw" after the call to the parent constructor, which initialises the dynamic tags. The current call is trying to set a value in a data structure that is yet to exist.

[BUG] set dynamic tag after call to parent constructor

---

README.md

adds a link and bibtex to the end of the readme, which seems to be the standard way of doing this.

[DOC] Add JMLR paper to readme

---

docs/papers_using_aeon.md

This adds papers, which are using the aeon-toolkit.
- the WEASEL v2 paper
- Human Activity Segmentation Challenge

[DOC, ENH] Add WEASEL v2 and Human Activity Challenge Papers

---

aeon/distances/_paa_sax_mindist.py
aeon/distances/_sax_mindist.py

This fixes an issue with lower bounding in iSAX. 
If the time series length is not divisible by the number of segments, PAA is padding some segments with 0. The concrete segments to pad are determined using `np.array_split()`.
To hold lower bounding, each segment's mean must thus be multiplied by the exact number of values it represents, again using `np.array_split()`.

[ENH, BUG] Fixes issue with lower bounding in SAX for TS length not divisible by the number of segments 

---

aeon/datasets/tests/test_tsad_data_loader.py
aeon/datasets/tests/test_tsad_datasets.py

fixes #2225
Fixes the tests for TSAD datasets:
- only downloads stuff from the internet in overnight tests
- hopefully prevents sporadic test failures by using a tmp folder for `local_data`
no

[BUG] Fix TSAD dataset tests

---

aeon/anomaly_detection/_copod.py
aeon/transformations/collection/dictionary_based/_borf.py
conftest.py

~~Fixes #2245~~  See #2254
~~Fixes the current periodic and main CI failures. `numba` `vectorize` is apparently not disabled by the environmental variable, so disabling  `njit` for the function called in it breaks it since it needs to be a numba function.~~
Fixes main branch CI issue. Mainly leftover `get_test_params` from PRs before the refactor. Adds some `pytest` options for multithreading and disabling numba

[MNT] CI fixes and pytest options

---

README.md

"Below we provide a quick example of how to use aeon for forecasting, classification and clustering." ->
"Below we provide a quick example of how to use aeon for classification and clustering."

[ENH] remove forecasting from readme

---

aeon/forecasting/__init__.py
aeon/forecasting/_ets.py
aeon/forecasting/_verify_ets.py
aeon/forecasting/base.py
aeon/forecasting/tests/test_ets.py

See also #2244
Adds full functionality to ETS model. Adds additional tests for this. Removes default argument form BaseForecaster.forecast method, as it is required to call BaseForecaster.fit(). Add code to verify ETS Forecaster against stats model.
It uses the statsforecast package to test against, it is optional

[ENH] Add Full ETS forecaster

---

.github/ISSUE_TEMPLATE/bug_report.yml

The `show_versions()`-utility is in the package `aeon` or `aeon.utils._maint` and cannot be imported from `aeon.utils`. This fixes the template to import from `aeon`.

[BUG] Fix bug_report.yml template show_versions

---

aeon/visualisation/results/_mcm.py

fixes #2358 sets the zero_method in mcm to "wilcox" to match scatter and cd diagrams

[ENH] fix the zero_method of the wilcoxon sign rank test to "wilcox" in mcm

---

aeon/transformations/collection/_impute.py
aeon/transformations/collection/tests/test_simple_imputer.py

Fixes a small bug in SimpleImputer #2347 . 
In my previous PR #2347 , I accidentally did not notice a bug. When `strategy` is a callable, it was fitting on 2d array instead of 1d array of independent case. I was about to correct it but the PR got merged. This PR fixes that bug and includes a test case for it.

[BUG] Bug fix in SimpleImputer

---

aeon/classification/feature_based/_catch22.py
aeon/classification/feature_based/_tsfresh.py
aeon/classification/feature_based/tests/__init__.py
aeon/classification/feature_based/tests/test_catch22.py
aeon/classification/feature_based/tests/test_signature.py
aeon/classification/feature_based/tests/test_summary.py
aeon/classification/feature_based/tests/test_tsfresh.py

adds some coverage for feature based classifiers. After core dev discussion, standardised model for public `self.estimator_` for estimator set in fit

[ENH] Tests for feature based classifiers

---

aeon/visualisation/results/_scatter.py

Fixes #2270 
Scaling of the minimum and maximum values by 0.97 and 1.03 is intended to provide a padding around the data range. However, if the data includes negative values (like -0.324397), the scaled minimum (min_value) will be closer to zero when multiplied by 0.97 thereby making it removing itself from the plot range. Therefore to resolve this we can multiply the negative values by 1.05 for min_values and 0.95 for max_values thereby making all points visible in the plot
Result:
No.

[BUG] Fixed Bug for negative values for scatter plot

---

docs/code_of_conduct.md
docs/governance.md
docs/index.md

For the most part both the code of conduct and governance remain the same, it is just minor language changes. The exception to this is an alteration to 
> All non-sensitive project management discussion takes place on the contributors channel on the project Slack and/or the issue tracker. Occasionally, sensitive discussion and votes such as appointments will occur in private Slack channels.
as this has turned out to not really match how we develop since the time the document was created. The changes here could be seen as an alteration of expected practice. 
The index page removes the big v1.0.0 warning, mention of forecasting (for now), and adds experimental modules.

[DOC] Tidy up `index`, `governance` and `code_of_conduct` pages.

---

aeon/clustering/deep_learning/_ae_abgru.py
aeon/clustering/deep_learning/_ae_bgru.py
aeon/clustering/deep_learning/_ae_dcnn.py
aeon/clustering/deep_learning/_ae_drnn.py
aeon/clustering/deep_learning/_ae_fcn.py
aeon/clustering/deep_learning/_ae_resnet.py
aeon/clustering/deep_learning/base.py

Part of #1518 
deprecating `clustering_algorithm` and `clustering_params` arguments as they were replaced by `estimator`

[MNT] Deprecation in deep clustering module

---

aeon/classification/distance_based/_proximity_tree.py
aeon/classification/distance_based/_time_series_neighbors.py
aeon/clustering/_clara.py
aeon/clustering/_clarans.py
aeon/clustering/_elastic_som.py
aeon/clustering/_k_means.py
aeon/clustering/_k_medoids.py
aeon/clustering/averaging/_ba_petitjean.py
aeon/clustering/averaging/_ba_subgradient.py
aeon/clustering/averaging/_ba_utils.py
aeon/clustering/averaging/_barycenter_averaging.py
aeon/distances/_distance.py
aeon/distances/elastic/tests/test_alignment_path.py
aeon/distances/elastic/tests/test_cost_matrix.py
aeon/distances/tests/test_distances.py
aeon/distances/tests/test_numba_distance_parameters.py
aeon/distances/tests/test_pairwise.py
aeon/regression/distance_based/_time_series_neighbors.py
aeon/transformations/collection/channel_selection/_elbow_class.py
aeon/transformations/series/tests/test_warping.py
examples/distances/distances.ipynb
examples/pydata/Amsterdam-2023/Lets_do_the_time_warp_again.ipynb

#2379
This PR changes the "metric" parameter to "measure" for the distance module. The reason for this is not all distance functions are metrics and therefore this parameter doesn't make sense for all distances.

[MNT] Change the "metric" parameter to "measure in the distance module

---

docs/developer_guide/adding_typehints.md

Added a documentation file about adding type hints
Fixes  #1857
This adds a file to the developers_guide and the file contains a guide to adding type hints in the project

[DOC] Created a adding_typehints.md in developers_guide that Fixes issue #1857

---

aeon/classification/deep_learning/_fcn.py

[DOC] Inserting the right paper reference

---

aeon/clustering/__init__.py
aeon/clustering/_kasba.py
aeon/clustering/averaging/__init__.py
aeon/clustering/averaging/_kasba_average.py
aeon/clustering/tests/test_kasba.py
docs/api_reference/clustering.rst
docs/papers_using_aeon.md

This PR adds KASBA to aeon. KASBA is a fast and accurate clusterer we developed. More details can be found here: https://arxiv.org/abs/2411.17838

[ENH] KASBA clusterer

---

aeon/regression/base.py
aeon/transformations/collection/base.py

corrects a few formatting issues in BaseCollectionTransformer and BaseClassifier. missing ticks and incorrect indentation (see #2444)

[DOC] Base collection class docstring formatting

---

aeon/classification/deep_learning/_lite_time.py

State that Keras Metrics class objects (and functions) can be used. Also link to the Keras documentation.
Closes #2435 
Maybe this change is also relevant for other Keras-based (tensorflow-based) estimators?

[DOC] LITE Time classifier metrics

---

docs/developer_guide/documentation.md

Fixes #2467 
Includes a note to install [Pandoc](https://pandoc.org/)
No.

[DOC] add note to install pandoc

---

aeon/classification/sklearn/_continuous_interval_tree.py
aeon/classification/sklearn/_rotation_forest_classifier.py
aeon/regression/sklearn/_rotation_forest_regressor.py

Fixes #1928 
Fixed incorrect type hinting in private methods for _TreeNode and PCA
1. Changed type hint for the `_find_splits_gain` method in _continuous_interval_tree.py from `type[_TreeNode]` to `_TreeNode`.
2.  Updated the type hint for `pcas` in `_predict_for_estimator` and `_predict_proba_for_estimator` methods in _rotation_forest_classifier.py and _rotation_forest_regressor.py from `type[PCA]` to `PCA`.
The changes correct type hints by using class instances instead of class types for _TreeNode and PCA.
No

[MNT] Fixed wrong type annotations for aeon classes

---

aeon/anomaly_detection/_cblof.py
aeon/anomaly_detection/_copod.py
aeon/anomaly_detection/_dwt_mlead.py
aeon/anomaly_detection/_iforest.py
aeon/anomaly_detection/_kmeans.py
aeon/anomaly_detection/_left_stampi.py
aeon/anomaly_detection/_lof.py
aeon/anomaly_detection/_merlin.py
aeon/anomaly_detection/_one_class_svm.py
aeon/anomaly_detection/_pyodadapter.py
aeon/anomaly_detection/_stomp.py
aeon/anomaly_detection/_stray.py
docs/conf.py

Fixes #1430 
Add `html-page-context` callback event to add capabilities table individually to each estimators' docs
- implement `_add_estimator_capabilities_table` function
- use that function with `html-page-context` sphinx event callback
No, it doesn't.

[ENH] Add sphinx event to add capability table to estimators' docs individually

---

aeon/classification/deep_learning/_cnn.py
aeon/networks/_cnn.py

Fixes #2307 
Added strides_pooling to the TimeCNNNetwork class as well as TimeCNNClassifier class to allow independent configuration of strides for pooling layers while ensuring backward compatibility by defaulting to avg_pool_size if not specified, and also added checks to ensure the size if a list is provided.
No
@all-contributors please add @kavya-r30 for code

[ENH] Added possibility for pooling strides in TimeCNN

---

docs/conf.py
docs/estimator_overview.md

Fixes #1438 
Added search functionality and page sorting for estimator overview table
No
@all-contributors please add @kavya-r30  for code

[DOC] Added search functionality for estimator overview table

---

aeon/clustering/deep_learning/_ae_abgru.py
aeon/clustering/deep_learning/_ae_bgru.py
aeon/clustering/deep_learning/_ae_dcnn.py
aeon/clustering/deep_learning/_ae_drnn.py
aeon/clustering/deep_learning/_ae_fcn.py
aeon/clustering/deep_learning/_ae_resnet.py

Fixes #1794 
Removes the Reshape layer from all the references in the `aeon\clustering\`
No
@all-contributors please add @kavya-r30 for code

[ENH] Removed Reshape Layer from Deep Learning Clusterers

---

aeon/classification/deep_learning/_lite_time.py

Fixes #2500 
Passes the stride parameter of LITETimeClassifier to IndividualLITEClassifier
No

[BUG] Passed stride parameter to LITETimeClassifier

---

docs/_static/css/custom.css

Fixes #1283 
Updated styles to make the dataframe tables more accessible in the dark mode.
No

[DOC] Update custom CSS for dataframe styling in documentation

---

aeon/classification/convolution_based/_mr_hydra.py

To solve issue #2434
- Updated the class_weight parameter docstring in MultiRocketHydraClassifier to clarify supported values.
- Explicitly mentioned that "balanced_subsample" is not supported as it is specific to ensemble models and not applicable to RidgeClassifierCV.

[DOC] Updated docstring to clarify class_weight parameter in MRHydraClassifier

---

aeon/classification/dictionary_based/_redcomets.py

Closes: #1742 
Replace SFA with the faster version, SFAFast.
None

[ENH] Replace SFA with SFAFast in REDCOMETS

---

aeon/classification/dictionary_based/tests/test_redcomets.py
aeon/testing/testing_config.py

Temporarily suppress failing tests to reduce impact on other PRs. This should be fixed before the next release.

[MNT] Temporary exclusion of REDCOMETS from CI

---

aeon/networks/tests/test_ae_resnet.py

Contributes to a part of #2497.
The following implementation adds test cases for every parameter of AEResNetNetwork in networks module. 
No
This update ensures better maintainability of the AEResNetNetwork class by testing edge cases for various configurations

[ENH] Test coverage for AEResNetNetwork Improved

---

aeon/transformations/series/__init__.py
docs/api_reference/transformations.rst

Fixes part of #2548.
Add both class to `__init__ ` `__all__`
No.
No.

[BUG] add ExpSmoothingSeriesTransformer and MovingAverageSeriesTransformer to __init__

---

aeon/networks/tests/test_mlp.py

Contributes to #2497 
Adds test coverage for _mlp.py
No
Achieves 96% coverage on _mlp.py, checked using 
```pytest --cov=aeon.networks aeon/networks/ ```

[ENH] Test coverage for MLP Network improved

---

aeon/classification/dictionary_based/_cboss.py
aeon/networks/tests/test_ae_fcn.py

Contributes to #2497.
Improves the test coverage for AEFCNNetwork.
No
No

[ENH] Test coverage for AEFCNNetwork Improved 

---

docs/conf.py
docs/index.md

Adds an advertisement for our GSoC project and instructions to the front page.

[DOC] Add GSoC announcement to web page

---

aeon/classification/dictionary_based/_redcomets.py
aeon/testing/testing_config.py

Fixes a bug introduced in the last REDCOMETs PR. Between its creation and merge there was an update to SFA fast which broke everything.

[MNT] Remove REDCOMETs from testing exclusion list

---

.github/utilities/run_examples.sh
.github/workflows/periodic_tests.yml
.github/workflows/pr_examples.yml

Fixes #2665
- Changed the os in the workflows for `pr_examples` and `periodic_tests` to `macos-latest`.
- Changed the workflow to install `bash 5.x` before running `run_examples.sh`
as lastpipe isnt available in `bash 3.2` which is in the github runner image for `macos-latest` (https://github.com/actions/runner-images/blob/main/images/macos/macos-15-arm64-Readme.md).
- Also added a step to install `boost` and `esig` before the `run_examples.sh` as `esig` is not installed on Darwin since its excluded in `pyproject.toml`.
No

[MNT] Use MacOS for examples/ workflow

---

docs/developer_guide/dependencies.md

No.
I found a typo (it should be) and corrected it.
No.
No.

[DOC]Update dependencies.md

---

aeon/visualisation/distances/tests/__init__.py
aeon/visualisation/distances/tests/test_pairwise_distance_matrix.py

Fixes #2562 
Test for pairwise distance matrix of visualisation distances

[ENH] Test Coverage for Pairwise Distance

---

aeon/visualisation/distances/_pairwise_distance_matrix.py

Fixes #2595 
Added Missing Docstring for pairwise distance matrix of visualisation distances

[DOC] Added Missing Docstring for Plot Pairwise Distance Matrix

---

.github/utilities/run_examples.sh

We do not install `esig` on macOS currently so we do not want to run this.

[MNT] Fix run_examples.sh exclusion

---

aeon/transformations/collection/feature_based/_summary.py
aeon/transformations/collection/feature_based/tests/test_summary.py

Fixes the values for the "percentiles" input and renames it to "quantiles".

[BUG] SevenNumberSummary bugfix and input rename

---

aeon/clustering/dummy.py

Adds tags to let dummy clusterer handle multivariate, unequal length and missing values.

[ENH] Add dummy clusterer tags

---

.github/workflows/fast_release.yml
.github/workflows/release.yml
docs/developer_guide/release.md

Updates release workflows to use trusted publishing. I have removed the old API keys after the latest security issue and would rather update to this than add new GitHub secrets. This adds a new step the release workflow must be approved by release workgroup members.

[MNT] Updated the release workflows

---

aeon/base/_compose.py
aeon/classification/dictionary_based/_redcomets.py
aeon/clustering/_kernel_k_means.py
aeon/distances/elastic/_bounding_matrix.py
aeon/regression/deep_learning/_lite_time.py
aeon/segmentation/_ggs.py
aeon/transformations/collection/convolution_based/_minirocket.py
aeon/transformations/series/_bkfilter.py
aeon/utils/show_versions.py
aeon/visualisation/results/_critical_difference.py
docs/_sphinxext/sphinx_remove_toctrees.py

Some missing bits from previous PRs.

[DOC] Add implementation references

---

.github/workflows/periodic_tests.yml
.github/workflows/pr_examples.yml
.github/workflows/release.yml

In PRs we use the CPU version of `torch`/`tensorflow` for faster installs. Time spent is not as important for the periodic tests, so it would be better to test the regular install use case here. It is possible that there could be subtle differences between these installs i.e. versioning for other dependencies.
May end up reverting if it turns out to be more pain than its worth.

[MNT] Use GPU installs for periodic tests

---

aeon/transformations/collection/interval_based/_quant.py

Fixes #2722 
Used direct shape calculations for `representation_functions` in `_fit` method of `QUANTTransformer`instead of unnecessary operations as only the output shapes are required to create the intervals.
No
The output correctly matches for the example given in the docstring.

[ENH] Optimize QUANTTransformer by using shape calculation in _fit method to avoid unnecessary computations

---

aeon/classification/distance_based/_time_series_neighbors.py

Addresses part of #1766.
Adds the "Raises" section to the `__init__` docstring of `KNeighborsTimeSeriesClassifier`.
Documents the verified `ValueError` raised during initialization when an unsupported string or an invalid callable is provided to the `weights` parameter.
This update improves user guidance by clarifying expected exceptions and aligns with Aeon's documentation standards.
No new dependencies introduced.
This contribution is part of my preparation and engagement for GSoC 2025, aligned with Aeon's project list.  
I am grateful for any feedback to improve this PR and my future contributions.

[DOC] Add Raises section for invalid `weights` in KNeighborsTimeSeriesClassifier (#1766)

---

CODEOWNERS

We moved the metrics into the `benchmarking` module. However, we forgot to update the `CODEOWNERS`-file, respectively. It's now fixed.

Fix codeowners for AD metrics

---

docs/governance.md

Adds a new role which is essentially just giving a person write access. Difference from core devs:
- No access to the core developer or voting Slack channels
- Any core dev can nominate someone for the role, just have to notify other developers in Slack and make a PR
- No vote as long as there is no veto by any core developer. That veto right remains for the duration and can be invoked if anyone thinks they are a detriment (i.e. acting like an ass or abusing review powers)
- Removed with inactivity
Essentially a stepping stone between regular contributor and core dev. Main target would be stuff like PhD students, interns or just people we want to get a bit more involved in the project without going through the whole process. Of course if people want to become core devs the same process …

[GOV] Supporting Developer role

---

aeon/classification/feature_based/_summary.py
aeon/clustering/feature_based/_summary.py
aeon/regression/feature_based/_summary.py

[DOC] Changed SummaryClusterer's summary_stat from "percentiles" to "quantiles"

---

aeon/networks/_ae_abgru.py
aeon/networks/tests/test_ae_abgru.py

Contributes to #2497. Reference PRs #2518 and #2534.
The given issue improvises the test coverage of AEAttentionBiGRUNetwork class.
No.
No.

[ENH] Test coverage for AEAttentionBiGRUNetwork Improved

---

pyproject.toml

The beginning of keras3 had lots of bugs, logical because of the huge change, but i prefer adding a lower bound, as the more i use older version than 3.6.0 the more i notice bugs that can lead to false research results
Example:
with keras 3.0 it discards the "trainable" boolean of a tensorflow operation, making for instance LITE work differently (unreported issue).
This is to archive for future references

[MNT] Lower bound keras to discard old bugged versions of early keras3

---

aeon/classification/distance_based/_time_series_neighbors.py

Fixes #2478. See also #2545 and #2578.
Uses n_jobs parameter in `_predict` and `predict_proba` of `KNeighborsTimeSeriesClassifier`. Parallelization is done in these methods instead of `_kneighbors` to potentially allow speedup through upper bounding the distance.

[ENH]Use n_jobs parameter in KNeighborsTimeSeriesClassifier.

---

aeon/clustering/_kernel_k_means.py
aeon/clustering/tests/test_kernel_k_means.py

Fixes the indexing errors in the implementation of the kernel DTW introduced by porting the Matlab (1-base indexing) code to Python (0-based indexing).
no

[BUG] Fix indexing errors in kdtw of KernelKMeans

---

aeon/similarity_search/series/_commons.py
aeon/similarity_search/series/motifs/_stomp.py
aeon/similarity_search/series/neighbors/_dummy.py
aeon/similarity_search/series/neighbors/_mass.py

This PR addresses issue #809 by standardizing the use of double backticks (``) for inline code references in the similarity_search module. Previously, some docstrings inconsistently used single backticks (`), which rendered text as italics instead of formatted code.
Changes made:
Replaced inconsistent single backticks with double backticks for inline code references.
Ensured uniform formatting across the following files:
aeon/similarity_search/base.py
aeon/similarity_search/distance_profiles/euclidean_distance_profile.py
aeon/similarity_search/distance_profiles/squared_distance_profile.py
aeon/similarity_search/matrix_profiles/stomp.py
aeon/similarity_search/query_search.py
aeon/similarity_search/series_search.py
Maintained readability and adherence to the Aeon documentation guidelines. …

[DOC] Fix inconsistent double backticks in similarity_search module (#809)

---

aeon/transformations/collection/convolution_based/_minirocket.py
aeon/transformations/collection/convolution_based/_multirocket.py

Fixes https://github.com/aeon-toolkit/aeon/issues/2179
removes the typing from numba, which was slowing down the cache building considerably, see issue for discussion
seems I have corrupted my local main branch again, ignore the arima first commit

[BUG] Remove typing from numba functions

---

aeon/benchmarking/metrics/anomaly_detection/_continuous.py
pyproject.toml

[DEP] Remove `prts` dependency

---

aeon/forecasting/_ets.py
aeon/forecasting/base.py
aeon/forecasting/tests/test_base.py
aeon/utils/tags/_tags.py

resolves #2814 
two tags to describe forecaster boolean capabilities
"capability": "horizon" indicates if the forecaster can directly fit a model to a horizon greater than one or not. Default True, but set false for ETS and ARIMA cannot. 
"capability": "exogenous" indicates if the forecaster can use egonenous variables in the modelling. Default False
both are tested in fit in BaseForecaster. I may have to do more to add tags, not sure about testing.

[ENH] Add two forecasting tags

---

.github/actions/cpu_all_extras/action.yml
.github/workflows/periodic_tests.yml
.github/workflows/pr_examples.yml
.github/workflows/pr_pytest.yml
.github/workflows/release.yml
aeon/transformations/collection/dictionary_based/_borf.py
pyproject.toml

- Updates actions to use Python 3.13.5 where relevant to avoid an issue with numba and 3.13.4 which is now fixed. For some reason the CI was still using 3.13.4 when not specifying to use the latest.
- Reduce the amount of swap space requested as sometimes we get an error for requesting to much (this is recent. no idea why)
- Separate doctests out into its own action and stops running doctests in other workflows. This is mainly because of the coverage test failure currently happening on all codecov runs where a bunch of doctests have different output when numba is disables
- an alternative is to just skip the doctests that are failing, but this is tedious and will probably reoccur down the line
- another alternative is to keep doctests on all regular pytest runs and disable it only for …

[MNT] Fixing CI issues and separate doctests from regular CI runners

---

aeon/transformations/collection/dictionary_based/_sfa_fast.py
aeon/transformations/collection/dictionary_based/tests/test_sfa.py

This PR fixes a bug with SFAFast throwing an error when calling `transform()` after `fit()`
As reported by @baraline SFAFast had the following error:
```python
from aeon.datasets import load_classification
from aeon.transformations.collection.dictionary_based import SFAFast
X_train, y_train = load_classification("SmoothSubspace", split="train")
SFAFast().fit(X_train, y_train).transform(X_train, y_train)
```
results in
```
File ~\Documents\aeon\aeon\transformations\collection\dictionary_based\_sfa_fast.py:1245, in create_bag_transform(X_index, feature_count, feature_selection, relevant_features, sfa_words, remove_repeat_words)
1241         all_win_words[j, :] = np.bincount(
1242             sfa_words[j][masked], minlength=feature_count
1243         )
1244     else:
-> 1245 …
```

[BUG] Fixes a bug with SFAFast throwing an error when calling transform after fit

---

.github/workflows/periodic_tests.yml
.github/workflows/pr_pytest.yml
.github/workflows/release.yml

The CI occasionally fails because it cant find enough space for swap storage. The added action makes more space.

[MNT] Clean disk space for CI to try stop sporadic failure

---

aeon/segmentation/base.py

#2958 
[fchavelli](https://github.com/aeon-toolkit/aeon/issues?q=is%3Aissue%20state%3Aopen%20author%3Afchavelli) spotted that y was being overwritten by check_y in the BaseSegmenter. Since we do not have any supervised/semi-supervised segmenters, we had not  noticed,  so thanks for spotting this. Simple fix

[BUG] stop overwriting y in BaseSegmenter

---

aeon/transformations/collection/convolution_based/_multirocket.py

Update variables `combination_index` and `n_channels_start` in loop for first order difference.
Fixes #2967
Ensures variables `combination_index` and `n_channels_start` are updated in loop for function _transform_multi for the first order difference.

[BUG] Fix multirocket bug variables not updated in loop

---

aeon/forecasting/base.py

Fixes #2999 
adds an axis to fit and predict, default to 1 as elsewhere, and requires forecast, direct_forecast and iterative_forecast to be passed series with axis = 1

[ENH] Add axis to base forecaster

---

aeon/distances/elastic/_msm.py

Our MSM cost matrix initialisation passed the values in the wrong order to the cost function. This is aeons MSM cost matrix initilisation:
```python3
for i in range(1, x_size):
if bounding_matrix[i, 0]:
cost = _cost_independent(x[i], x[i - 1], y[0], c)
cost_matrix[i][0] = cost_matrix[i - 1][0] + cost
for i in range(1, y_size):
if bounding_matrix[0, i]:
cost = _cost_independent(y[i], y[i - 1], x[0], c)  # <------ This line is wrong
cost_matrix[0][i] = cost_matrix[0][i - 1] + cost
```
In the original paper is show that it should be _cost_independent(y[i], x[0], y[i - 1], c). 
See:
Source: https://ieeexplore.ieee.org/document/6189346
This PR fixes this minor bug.
This should never really impact any results (I haven't changed any tests that check for expected results) just a minor edge case …

[BUG] MSM cost matrix initialisation bug fix.

---

aeon/testing/data_generation/__init__.py
aeon/testing/data_generation/_labels.py
aeon/testing/data_generation/_series.py
aeon/testing/data_generation/tests/test_labels.py
aeon/testing/data_generation/tests/test_series.py
aeon/testing/testing_data.py
aeon/testing/tests/test_testing_data.py

The current testing data for series estimators is rather shallow as around the time of the rework most series modules were much more experimental. Now that more work is going in to these modules i.e. anomaly detection and forecasting this PR expands the testing data available in the general testing and formats it more like the collection sets. For now the options are no labels and anomaly labels, but it is easy to expand this.

[ENH] Update testing data dictionary with series testing data

---

aeon/clustering/deep_learning/_ae_dcnn.py
aeon/clustering/deep_learning/_ae_drnn.py

[BUG] FIX DRNN load bug
